add_rules("mode.debug", "mode.release")
--add SDL require
add_requires("SDL2","SDL2_image","SDL2_ttf","SDL2_gfx")
add_cxxflags("-std=c++17")
add_includedirs("include")
target("btk")
    add_links("SDL2")
    set_kind("shared")
    add_files("./src/impl/*.cpp")
    add_files("./src/*.cpp")
target("hello")
    set_kind("binary")
    add_files("./tests/hello.cpp")
    add_deps("btk")