/*

    OpenGL ES loader generated by Btk 0.1.34 on Sat Jul 31 12:37:15 2021.

    Language/Generator: C/C++
    Specification: gl
    APIs: gles2=3.2
    Profile: core
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="core" --api="gles2=3.2" --generator="c" --spec="gl" --extensions=""
    Online:
        https://Btk.dav1d.de/#profile=core&language=c&specification=gl&loader=on&api=gles2%3D3.2
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <Btk/gl/glad.h>

struct BtkGLversionStruct GLVersion = { 0, 0 };

#if defined(GL_ES_VERSION_3_0) || defined(GL_VERSION_3_0)
#define _GLAD_IS_SOME_NEW_VERSION 1
#endif

static int max_loaded_major;
static int max_loaded_minor;

static const char *exts = NULL;
static int num_exts_i = 0;
static char **exts_i = NULL;

static int get_exts(void) {
#ifdef _GLAD_IS_SOME_NEW_VERSION
    if(max_loaded_major < 3) {
#endif
        exts = (const char *)glGetString(GL_EXTENSIONS);
#ifdef _GLAD_IS_SOME_NEW_VERSION
    } else {
        unsigned int index;

        num_exts_i = 0;
        glGetIntegerv(GL_NUM_EXTENSIONS, &num_exts_i);
        if (num_exts_i > 0) {
            exts_i = (char **)malloc((size_t)num_exts_i * (sizeof *exts_i));
        }

        if (exts_i == NULL) {
            return 0;
        }

        for(index = 0; index < (unsigned)num_exts_i; index++) {
            const char *gl_str_tmp = (const char*)glGetStringi(GL_EXTENSIONS, index);
            size_t len = strlen(gl_str_tmp);

            char *local_str = (char*)malloc((len+1) * sizeof(char));
            if(local_str != NULL) {
                memcpy(local_str, gl_str_tmp, (len+1) * sizeof(char));
            }
            exts_i[index] = local_str;
        }
    }
#endif
    return 1;
}

static void free_exts(void) {
    if (exts_i != NULL) {
        int index;
        for(index = 0; index < num_exts_i; index++) {
            free((char *)exts_i[index]);
        }
        free((void *)exts_i);
        exts_i = NULL;
    }
}

static int has_ext(const char *ext) {
#ifdef _GLAD_IS_SOME_NEW_VERSION
    if(max_loaded_major < 3) {
#endif
        const char *extensions;
        const char *loc;
        const char *terminator;
        extensions = exts;
        if(extensions == NULL || ext == NULL) {
            return 0;
        }

        while(1) {
            loc = strstr(extensions, ext);
            if(loc == NULL) {
                return 0;
            }

            terminator = loc + strlen(ext);
            if((loc == extensions || *(loc - 1) == ' ') &&
                (*terminator == ' ' || *terminator == '\0')) {
                return 1;
            }
            extensions = terminator;
        }
#ifdef _GLAD_IS_SOME_NEW_VERSION
    } else {
        int index;
        if(exts_i == NULL) return 0;
        for(index = 0; index < num_exts_i; index++) {
            const char *e = exts_i[index];

            if(exts_i[index] != NULL && strcmp(e, ext) == 0) {
                return 1;
            }
        }
    }
#endif

    return 0;
}
int BTK_GL_ES_VERSION_2_0 = 0;
int BTK_GL_ES_VERSION_3_0 = 0;
int BTK_GL_ES_VERSION_3_1 = 0;
int BTK_GL_ES_VERSION_3_2 = 0;
PFNGLACTIVESHADERPROGRAMPROC Btk_glActiveShaderProgram = NULL;
PFNGLACTIVETEXTUREPROC Btk_glActiveTexture = NULL;
PFNGLATTACHSHADERPROC Btk_glAttachShader = NULL;
PFNGLBEGINQUERYPROC Btk_glBeginQuery = NULL;
PFNGLBEGINTRANSFORMFEEDBACKPROC Btk_glBeginTransformFeedback = NULL;
PFNGLBINDATTRIBLOCATIONPROC Btk_glBindAttribLocation = NULL;
PFNGLBINDBUFFERPROC Btk_glBindBuffer = NULL;
PFNGLBINDBUFFERBASEPROC Btk_glBindBufferBase = NULL;
PFNGLBINDBUFFERRANGEPROC Btk_glBindBufferRange = NULL;
PFNGLBINDFRAMEBUFFERPROC Btk_glBindFramebuffer = NULL;
PFNGLBINDIMAGETEXTUREPROC Btk_glBindImageTexture = NULL;
PFNGLBINDPROGRAMPIPELINEPROC Btk_glBindProgramPipeline = NULL;
PFNGLBINDRENDERBUFFERPROC Btk_glBindRenderbuffer = NULL;
PFNGLBINDSAMPLERPROC Btk_glBindSampler = NULL;
PFNGLBINDTEXTUREPROC Btk_glBindTexture = NULL;
PFNGLBINDTRANSFORMFEEDBACKPROC Btk_glBindTransformFeedback = NULL;
PFNGLBINDVERTEXARRAYPROC Btk_glBindVertexArray = NULL;
PFNGLBINDVERTEXBUFFERPROC Btk_glBindVertexBuffer = NULL;
PFNGLBLENDBARRIERPROC Btk_glBlendBarrier = NULL;
PFNGLBLENDCOLORPROC Btk_glBlendColor = NULL;
PFNGLBLENDEQUATIONPROC Btk_glBlendEquation = NULL;
PFNGLBLENDEQUATIONSEPARATEPROC Btk_glBlendEquationSeparate = NULL;
PFNGLBLENDEQUATIONSEPARATEIPROC Btk_glBlendEquationSeparatei = NULL;
PFNGLBLENDEQUATIONIPROC Btk_glBlendEquationi = NULL;
PFNGLBLENDFUNCPROC Btk_glBlendFunc = NULL;
PFNGLBLENDFUNCSEPARATEPROC Btk_glBlendFuncSeparate = NULL;
PFNGLBLENDFUNCSEPARATEIPROC Btk_glBlendFuncSeparatei = NULL;
PFNGLBLENDFUNCIPROC Btk_glBlendFunci = NULL;
PFNGLBLITFRAMEBUFFERPROC Btk_glBlitFramebuffer = NULL;
PFNGLBUFFERDATAPROC Btk_glBufferData = NULL;
PFNGLBUFFERSUBDATAPROC Btk_glBufferSubData = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC Btk_glCheckFramebufferStatus = NULL;
PFNGLCLEARPROC Btk_glClear = NULL;
PFNGLCLEARBUFFERFIPROC Btk_glClearBufferfi = NULL;
PFNGLCLEARBUFFERFVPROC Btk_glClearBufferfv = NULL;
PFNGLCLEARBUFFERIVPROC Btk_glClearBufferiv = NULL;
PFNGLCLEARBUFFERUIVPROC Btk_glClearBufferuiv = NULL;
PFNGLCLEARCOLORPROC Btk_glClearColor = NULL;
PFNGLCLEARDEPTHFPROC Btk_glClearDepthf = NULL;
PFNGLCLEARSTENCILPROC Btk_glClearStencil = NULL;
PFNGLCLIENTWAITSYNCPROC Btk_glClientWaitSync = NULL;
PFNGLCOLORMASKPROC Btk_glColorMask = NULL;
PFNGLCOLORMASKIPROC Btk_glColorMaski = NULL;
PFNGLCOMPILESHADERPROC Btk_glCompileShader = NULL;
PFNGLCOMPRESSEDTEXIMAGE2DPROC Btk_glCompressedTexImage2D = NULL;
PFNGLCOMPRESSEDTEXIMAGE3DPROC Btk_glCompressedTexImage3D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC Btk_glCompressedTexSubImage2D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC Btk_glCompressedTexSubImage3D = NULL;
PFNGLCOPYBUFFERSUBDATAPROC Btk_glCopyBufferSubData = NULL;
PFNGLCOPYIMAGESUBDATAPROC Btk_glCopyImageSubData = NULL;
PFNGLCOPYTEXIMAGE2DPROC Btk_glCopyTexImage2D = NULL;
PFNGLCOPYTEXSUBIMAGE2DPROC Btk_glCopyTexSubImage2D = NULL;
PFNGLCOPYTEXSUBIMAGE3DPROC Btk_glCopyTexSubImage3D = NULL;
PFNGLCREATEPROGRAMPROC Btk_glCreateProgram = NULL;
PFNGLCREATESHADERPROC Btk_glCreateShader = NULL;
PFNGLCREATESHADERPROGRAMVPROC Btk_glCreateShaderProgramv = NULL;
PFNGLCULLFACEPROC Btk_glCullFace = NULL;
PFNGLDEBUGMESSAGECALLBACKPROC Btk_glDebugMessageCallback = NULL;
PFNGLDEBUGMESSAGECONTROLPROC Btk_glDebugMessageControl = NULL;
PFNGLDEBUGMESSAGEINSERTPROC Btk_glDebugMessageInsert = NULL;
PFNGLDELETEBUFFERSPROC Btk_glDeleteBuffers = NULL;
PFNGLDELETEFRAMEBUFFERSPROC Btk_glDeleteFramebuffers = NULL;
PFNGLDELETEPROGRAMPROC Btk_glDeleteProgram = NULL;
PFNGLDELETEPROGRAMPIPELINESPROC Btk_glDeleteProgramPipelines = NULL;
PFNGLDELETEQUERIESPROC Btk_glDeleteQueries = NULL;
PFNGLDELETERENDERBUFFERSPROC Btk_glDeleteRenderbuffers = NULL;
PFNGLDELETESAMPLERSPROC Btk_glDeleteSamplers = NULL;
PFNGLDELETESHADERPROC Btk_glDeleteShader = NULL;
PFNGLDELETESYNCPROC Btk_glDeleteSync = NULL;
PFNGLDELETETEXTURESPROC Btk_glDeleteTextures = NULL;
PFNGLDELETETRANSFORMFEEDBACKSPROC Btk_glDeleteTransformFeedbacks = NULL;
PFNGLDELETEVERTEXARRAYSPROC Btk_glDeleteVertexArrays = NULL;
PFNGLDEPTHFUNCPROC Btk_glDepthFunc = NULL;
PFNGLDEPTHMASKPROC Btk_glDepthMask = NULL;
PFNGLDEPTHRANGEFPROC Btk_glDepthRangef = NULL;
PFNGLDETACHSHADERPROC Btk_glDetachShader = NULL;
PFNGLDISABLEPROC Btk_glDisable = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC Btk_glDisableVertexAttribArray = NULL;
PFNGLDISABLEIPROC Btk_glDisablei = NULL;
PFNGLDISPATCHCOMPUTEPROC Btk_glDispatchCompute = NULL;
PFNGLDISPATCHCOMPUTEINDIRECTPROC Btk_glDispatchComputeIndirect = NULL;
PFNGLDRAWARRAYSPROC Btk_glDrawArrays = NULL;
PFNGLDRAWARRAYSINDIRECTPROC Btk_glDrawArraysIndirect = NULL;
PFNGLDRAWARRAYSINSTANCEDPROC Btk_glDrawArraysInstanced = NULL;
PFNGLDRAWBUFFERSPROC Btk_glDrawBuffers = NULL;
PFNGLDRAWELEMENTSPROC Btk_glDrawElements = NULL;
PFNGLDRAWELEMENTSBASEVERTEXPROC Btk_glDrawElementsBaseVertex = NULL;
PFNGLDRAWELEMENTSINDIRECTPROC Btk_glDrawElementsIndirect = NULL;
PFNGLDRAWELEMENTSINSTANCEDPROC Btk_glDrawElementsInstanced = NULL;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC Btk_glDrawElementsInstancedBaseVertex = NULL;
PFNGLDRAWRANGEELEMENTSPROC Btk_glDrawRangeElements = NULL;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC Btk_glDrawRangeElementsBaseVertex = NULL;
PFNGLENABLEPROC Btk_glEnable = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC Btk_glEnableVertexAttribArray = NULL;
PFNGLENABLEIPROC Btk_glEnablei = NULL;
PFNGLENDQUERYPROC Btk_glEndQuery = NULL;
PFNGLENDTRANSFORMFEEDBACKPROC Btk_glEndTransformFeedback = NULL;
PFNGLFENCESYNCPROC Btk_glFenceSync = NULL;
PFNGLFINISHPROC Btk_glFinish = NULL;
PFNGLFLUSHPROC Btk_glFlush = NULL;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC Btk_glFlushMappedBufferRange = NULL;
PFNGLFRAMEBUFFERPARAMETERIPROC Btk_glFramebufferParameteri = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC Btk_glFramebufferRenderbuffer = NULL;
PFNGLFRAMEBUFFERTEXTUREPROC Btk_glFramebufferTexture = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC Btk_glFramebufferTexture2D = NULL;
PFNGLFRAMEBUFFERTEXTURELAYERPROC Btk_glFramebufferTextureLayer = NULL;
PFNGLFRONTFACEPROC Btk_glFrontFace = NULL;
PFNGLGENBUFFERSPROC Btk_glGenBuffers = NULL;
PFNGLGENFRAMEBUFFERSPROC Btk_glGenFramebuffers = NULL;
PFNGLGENPROGRAMPIPELINESPROC Btk_glGenProgramPipelines = NULL;
PFNGLGENQUERIESPROC Btk_glGenQueries = NULL;
PFNGLGENRENDERBUFFERSPROC Btk_glGenRenderbuffers = NULL;
PFNGLGENSAMPLERSPROC Btk_glGenSamplers = NULL;
PFNGLGENTEXTURESPROC Btk_glGenTextures = NULL;
PFNGLGENTRANSFORMFEEDBACKSPROC Btk_glGenTransformFeedbacks = NULL;
PFNGLGENVERTEXARRAYSPROC Btk_glGenVertexArrays = NULL;
PFNGLGENERATEMIPMAPPROC Btk_glGenerateMipmap = NULL;
PFNGLGETACTIVEATTRIBPROC Btk_glGetActiveAttrib = NULL;
PFNGLGETACTIVEUNIFORMPROC Btk_glGetActiveUniform = NULL;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC Btk_glGetActiveUniformBlockName = NULL;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC Btk_glGetActiveUniformBlockiv = NULL;
PFNGLGETACTIVEUNIFORMSIVPROC Btk_glGetActiveUniformsiv = NULL;
PFNGLGETATTACHEDSHADERSPROC Btk_glGetAttachedShaders = NULL;
PFNGLGETATTRIBLOCATIONPROC Btk_glGetAttribLocation = NULL;
PFNGLGETBOOLEANI_VPROC Btk_glGetBooleani_v = NULL;
PFNGLGETBOOLEANVPROC Btk_glGetBooleanv = NULL;
PFNGLGETBUFFERPARAMETERI64VPROC Btk_glGetBufferParameteri64v = NULL;
PFNGLGETBUFFERPARAMETERIVPROC Btk_glGetBufferParameteriv = NULL;
PFNGLGETBUFFERPOINTERVPROC Btk_glGetBufferPointerv = NULL;
PFNGLGETDEBUGMESSAGELOGPROC Btk_glGetDebugMessageLog = NULL;
PFNGLGETERRORPROC Btk_glGetError = NULL;
PFNGLGETFLOATVPROC Btk_glGetFloatv = NULL;
PFNGLGETFRAGDATALOCATIONPROC Btk_glGetFragDataLocation = NULL;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC Btk_glGetFramebufferAttachmentParameteriv = NULL;
PFNGLGETFRAMEBUFFERPARAMETERIVPROC Btk_glGetFramebufferParameteriv = NULL;
PFNGLGETGRAPHICSRESETSTATUSPROC Btk_glGetGraphicsResetStatus = NULL;
PFNGLGETINTEGER64I_VPROC Btk_glGetInteger64i_v = NULL;
PFNGLGETINTEGER64VPROC Btk_glGetInteger64v = NULL;
PFNGLGETINTEGERI_VPROC Btk_glGetIntegeri_v = NULL;
PFNGLGETINTEGERVPROC Btk_glGetIntegerv = NULL;
PFNGLGETINTERNALFORMATIVPROC Btk_glGetInternalformativ = NULL;
PFNGLGETMULTISAMPLEFVPROC Btk_glGetMultisamplefv = NULL;
PFNGLGETOBJECTLABELPROC Btk_glGetObjectLabel = NULL;
PFNGLGETOBJECTPTRLABELPROC Btk_glGetObjectPtrLabel = NULL;
PFNGLGETPOINTERVPROC Btk_glGetPointerv = NULL;
PFNGLGETPROGRAMBINARYPROC Btk_glGetProgramBinary = NULL;
PFNGLGETPROGRAMINFOLOGPROC Btk_glGetProgramInfoLog = NULL;
PFNGLGETPROGRAMINTERFACEIVPROC Btk_glGetProgramInterfaceiv = NULL;
PFNGLGETPROGRAMPIPELINEINFOLOGPROC Btk_glGetProgramPipelineInfoLog = NULL;
PFNGLGETPROGRAMPIPELINEIVPROC Btk_glGetProgramPipelineiv = NULL;
PFNGLGETPROGRAMRESOURCEINDEXPROC Btk_glGetProgramResourceIndex = NULL;
PFNGLGETPROGRAMRESOURCELOCATIONPROC Btk_glGetProgramResourceLocation = NULL;
PFNGLGETPROGRAMRESOURCENAMEPROC Btk_glGetProgramResourceName = NULL;
PFNGLGETPROGRAMRESOURCEIVPROC Btk_glGetProgramResourceiv = NULL;
PFNGLGETPROGRAMIVPROC Btk_glGetProgramiv = NULL;
PFNGLGETQUERYOBJECTUIVPROC Btk_glGetQueryObjectuiv = NULL;
PFNGLGETQUERYIVPROC Btk_glGetQueryiv = NULL;
PFNGLGETRENDERBUFFERPARAMETERIVPROC Btk_glGetRenderbufferParameteriv = NULL;
PFNGLGETSAMPLERPARAMETERIIVPROC Btk_glGetSamplerParameterIiv = NULL;
PFNGLGETSAMPLERPARAMETERIUIVPROC Btk_glGetSamplerParameterIuiv = NULL;
PFNGLGETSAMPLERPARAMETERFVPROC Btk_glGetSamplerParameterfv = NULL;
PFNGLGETSAMPLERPARAMETERIVPROC Btk_glGetSamplerParameteriv = NULL;
PFNGLGETSHADERINFOLOGPROC Btk_glGetShaderInfoLog = NULL;
PFNGLGETSHADERPRECISIONFORMATPROC Btk_glGetShaderPrecisionFormat = NULL;
PFNGLGETSHADERSOURCEPROC Btk_glGetShaderSource = NULL;
PFNGLGETSHADERIVPROC Btk_glGetShaderiv = NULL;
PFNGLGETSTRINGPROC Btk_glGetString = NULL;
PFNGLGETSTRINGIPROC Btk_glGetStringi = NULL;
PFNGLGETSYNCIVPROC Btk_glGetSynciv = NULL;
PFNGLGETTEXLEVELPARAMETERFVPROC Btk_glGetTexLevelParameterfv = NULL;
PFNGLGETTEXLEVELPARAMETERIVPROC Btk_glGetTexLevelParameteriv = NULL;
PFNGLGETTEXPARAMETERIIVPROC Btk_glGetTexParameterIiv = NULL;
PFNGLGETTEXPARAMETERIUIVPROC Btk_glGetTexParameterIuiv = NULL;
PFNGLGETTEXPARAMETERFVPROC Btk_glGetTexParameterfv = NULL;
PFNGLGETTEXPARAMETERIVPROC Btk_glGetTexParameteriv = NULL;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC Btk_glGetTransformFeedbackVarying = NULL;
PFNGLGETUNIFORMBLOCKINDEXPROC Btk_glGetUniformBlockIndex = NULL;
PFNGLGETUNIFORMINDICESPROC Btk_glGetUniformIndices = NULL;
PFNGLGETUNIFORMLOCATIONPROC Btk_glGetUniformLocation = NULL;
PFNGLGETUNIFORMFVPROC Btk_glGetUniformfv = NULL;
PFNGLGETUNIFORMIVPROC Btk_glGetUniformiv = NULL;
PFNGLGETUNIFORMUIVPROC Btk_glGetUniformuiv = NULL;
PFNGLGETVERTEXATTRIBIIVPROC Btk_glGetVertexAttribIiv = NULL;
PFNGLGETVERTEXATTRIBIUIVPROC Btk_glGetVertexAttribIuiv = NULL;
PFNGLGETVERTEXATTRIBPOINTERVPROC Btk_glGetVertexAttribPointerv = NULL;
PFNGLGETVERTEXATTRIBFVPROC Btk_glGetVertexAttribfv = NULL;
PFNGLGETVERTEXATTRIBIVPROC Btk_glGetVertexAttribiv = NULL;
PFNGLGETNUNIFORMFVPROC Btk_glGetnUniformfv = NULL;
PFNGLGETNUNIFORMIVPROC Btk_glGetnUniformiv = NULL;
PFNGLGETNUNIFORMUIVPROC Btk_glGetnUniformuiv = NULL;
PFNGLHINTPROC Btk_glHint = NULL;
PFNGLINVALIDATEFRAMEBUFFERPROC Btk_glInvalidateFramebuffer = NULL;
PFNGLINVALIDATESUBFRAMEBUFFERPROC Btk_glInvalidateSubFramebuffer = NULL;
PFNGLISBUFFERPROC Btk_glIsBuffer = NULL;
PFNGLISENABLEDPROC Btk_glIsEnabled = NULL;
PFNGLISENABLEDIPROC Btk_glIsEnabledi = NULL;
PFNGLISFRAMEBUFFERPROC Btk_glIsFramebuffer = NULL;
PFNGLISPROGRAMPROC Btk_glIsProgram = NULL;
PFNGLISPROGRAMPIPELINEPROC Btk_glIsProgramPipeline = NULL;
PFNGLISQUERYPROC Btk_glIsQuery = NULL;
PFNGLISRENDERBUFFERPROC Btk_glIsRenderbuffer = NULL;
PFNGLISSAMPLERPROC Btk_glIsSampler = NULL;
PFNGLISSHADERPROC Btk_glIsShader = NULL;
PFNGLISSYNCPROC Btk_glIsSync = NULL;
PFNGLISTEXTUREPROC Btk_glIsTexture = NULL;
PFNGLISTRANSFORMFEEDBACKPROC Btk_glIsTransformFeedback = NULL;
PFNGLISVERTEXARRAYPROC Btk_glIsVertexArray = NULL;
PFNGLLINEWIDTHPROC Btk_glLineWidth = NULL;
PFNGLLINKPROGRAMPROC Btk_glLinkProgram = NULL;
PFNGLMAPBUFFERRANGEPROC Btk_glMapBufferRange = NULL;
PFNGLMEMORYBARRIERPROC Btk_glMemoryBarrier = NULL;
PFNGLMEMORYBARRIERBYREGIONPROC Btk_glMemoryBarrierByRegion = NULL;
PFNGLMINSAMPLESHADINGPROC Btk_glMinSampleShading = NULL;
PFNGLOBJECTLABELPROC Btk_glObjectLabel = NULL;
PFNGLOBJECTPTRLABELPROC Btk_glObjectPtrLabel = NULL;
PFNGLPATCHPARAMETERIPROC Btk_glPatchParameteri = NULL;
PFNGLPAUSETRANSFORMFEEDBACKPROC Btk_glPauseTransformFeedback = NULL;
PFNGLPIXELSTOREIPROC Btk_glPixelStorei = NULL;
PFNGLPOLYGONOFFSETPROC Btk_glPolygonOffset = NULL;
PFNGLPOPDEBUGGROUPPROC Btk_glPopDebugGroup = NULL;
PFNGLPRIMITIVEBOUNDINGBOXPROC Btk_glPrimitiveBoundingBox = NULL;
PFNGLPROGRAMBINARYPROC Btk_glProgramBinary = NULL;
PFNGLPROGRAMPARAMETERIPROC Btk_glProgramParameteri = NULL;
PFNGLPROGRAMUNIFORM1FPROC Btk_glProgramUniform1f = NULL;
PFNGLPROGRAMUNIFORM1FVPROC Btk_glProgramUniform1fv = NULL;
PFNGLPROGRAMUNIFORM1IPROC Btk_glProgramUniform1i = NULL;
PFNGLPROGRAMUNIFORM1IVPROC Btk_glProgramUniform1iv = NULL;
PFNGLPROGRAMUNIFORM1UIPROC Btk_glProgramUniform1ui = NULL;
PFNGLPROGRAMUNIFORM1UIVPROC Btk_glProgramUniform1uiv = NULL;
PFNGLPROGRAMUNIFORM2FPROC Btk_glProgramUniform2f = NULL;
PFNGLPROGRAMUNIFORM2FVPROC Btk_glProgramUniform2fv = NULL;
PFNGLPROGRAMUNIFORM2IPROC Btk_glProgramUniform2i = NULL;
PFNGLPROGRAMUNIFORM2IVPROC Btk_glProgramUniform2iv = NULL;
PFNGLPROGRAMUNIFORM2UIPROC Btk_glProgramUniform2ui = NULL;
PFNGLPROGRAMUNIFORM2UIVPROC Btk_glProgramUniform2uiv = NULL;
PFNGLPROGRAMUNIFORM3FPROC Btk_glProgramUniform3f = NULL;
PFNGLPROGRAMUNIFORM3FVPROC Btk_glProgramUniform3fv = NULL;
PFNGLPROGRAMUNIFORM3IPROC Btk_glProgramUniform3i = NULL;
PFNGLPROGRAMUNIFORM3IVPROC Btk_glProgramUniform3iv = NULL;
PFNGLPROGRAMUNIFORM3UIPROC Btk_glProgramUniform3ui = NULL;
PFNGLPROGRAMUNIFORM3UIVPROC Btk_glProgramUniform3uiv = NULL;
PFNGLPROGRAMUNIFORM4FPROC Btk_glProgramUniform4f = NULL;
PFNGLPROGRAMUNIFORM4FVPROC Btk_glProgramUniform4fv = NULL;
PFNGLPROGRAMUNIFORM4IPROC Btk_glProgramUniform4i = NULL;
PFNGLPROGRAMUNIFORM4IVPROC Btk_glProgramUniform4iv = NULL;
PFNGLPROGRAMUNIFORM4UIPROC Btk_glProgramUniform4ui = NULL;
PFNGLPROGRAMUNIFORM4UIVPROC Btk_glProgramUniform4uiv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2FVPROC Btk_glProgramUniformMatrix2fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC Btk_glProgramUniformMatrix2x3fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC Btk_glProgramUniformMatrix2x4fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC Btk_glProgramUniformMatrix3fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC Btk_glProgramUniformMatrix3x2fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC Btk_glProgramUniformMatrix3x4fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4FVPROC Btk_glProgramUniformMatrix4fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC Btk_glProgramUniformMatrix4x2fv = NULL;
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC Btk_glProgramUniformMatrix4x3fv = NULL;
PFNGLPUSHDEBUGGROUPPROC Btk_glPushDebugGroup = NULL;
PFNGLREADBUFFERPROC Btk_glReadBuffer = NULL;
PFNGLREADPIXELSPROC Btk_glReadPixels = NULL;
PFNGLREADNPIXELSPROC Btk_glReadnPixels = NULL;
PFNGLRELEASESHADERCOMPILERPROC Btk_glReleaseShaderCompiler = NULL;
PFNGLRENDERBUFFERSTORAGEPROC Btk_glRenderbufferStorage = NULL;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC Btk_glRenderbufferStorageMultisample = NULL;
PFNGLRESUMETRANSFORMFEEDBACKPROC Btk_glResumeTransformFeedback = NULL;
PFNGLSAMPLECOVERAGEPROC Btk_glSampleCoverage = NULL;
PFNGLSAMPLEMASKIPROC Btk_glSampleMaski = NULL;
PFNGLSAMPLERPARAMETERIIVPROC Btk_glSamplerParameterIiv = NULL;
PFNGLSAMPLERPARAMETERIUIVPROC Btk_glSamplerParameterIuiv = NULL;
PFNGLSAMPLERPARAMETERFPROC Btk_glSamplerParameterf = NULL;
PFNGLSAMPLERPARAMETERFVPROC Btk_glSamplerParameterfv = NULL;
PFNGLSAMPLERPARAMETERIPROC Btk_glSamplerParameteri = NULL;
PFNGLSAMPLERPARAMETERIVPROC Btk_glSamplerParameteriv = NULL;
PFNGLSCISSORPROC Btk_glScissor = NULL;
PFNGLSHADERBINARYPROC Btk_glShaderBinary = NULL;
PFNGLSHADERSOURCEPROC Btk_glShaderSource = NULL;
PFNGLSTENCILFUNCPROC Btk_glStencilFunc = NULL;
PFNGLSTENCILFUNCSEPARATEPROC Btk_glStencilFuncSeparate = NULL;
PFNGLSTENCILMASKPROC Btk_glStencilMask = NULL;
PFNGLSTENCILMASKSEPARATEPROC Btk_glStencilMaskSeparate = NULL;
PFNGLSTENCILOPPROC Btk_glStencilOp = NULL;
PFNGLSTENCILOPSEPARATEPROC Btk_glStencilOpSeparate = NULL;
PFNGLTEXBUFFERPROC Btk_glTexBuffer = NULL;
PFNGLTEXBUFFERRANGEPROC Btk_glTexBufferRange = NULL;
PFNGLTEXIMAGE2DPROC Btk_glTexImage2D = NULL;
PFNGLTEXIMAGE3DPROC Btk_glTexImage3D = NULL;
PFNGLTEXPARAMETERIIVPROC Btk_glTexParameterIiv = NULL;
PFNGLTEXPARAMETERIUIVPROC Btk_glTexParameterIuiv = NULL;
PFNGLTEXPARAMETERFPROC Btk_glTexParameterf = NULL;
PFNGLTEXPARAMETERFVPROC Btk_glTexParameterfv = NULL;
PFNGLTEXPARAMETERIPROC Btk_glTexParameteri = NULL;
PFNGLTEXPARAMETERIVPROC Btk_glTexParameteriv = NULL;
PFNGLTEXSTORAGE2DPROC Btk_glTexStorage2D = NULL;
PFNGLTEXSTORAGE2DMULTISAMPLEPROC Btk_glTexStorage2DMultisample = NULL;
PFNGLTEXSTORAGE3DPROC Btk_glTexStorage3D = NULL;
PFNGLTEXSTORAGE3DMULTISAMPLEPROC Btk_glTexStorage3DMultisample = NULL;
PFNGLTEXSUBIMAGE2DPROC Btk_glTexSubImage2D = NULL;
PFNGLTEXSUBIMAGE3DPROC Btk_glTexSubImage3D = NULL;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC Btk_glTransformFeedbackVaryings = NULL;
PFNGLUNIFORM1FPROC Btk_glUniform1f = NULL;
PFNGLUNIFORM1FVPROC Btk_glUniform1fv = NULL;
PFNGLUNIFORM1IPROC Btk_glUniform1i = NULL;
PFNGLUNIFORM1IVPROC Btk_glUniform1iv = NULL;
PFNGLUNIFORM1UIPROC Btk_glUniform1ui = NULL;
PFNGLUNIFORM1UIVPROC Btk_glUniform1uiv = NULL;
PFNGLUNIFORM2FPROC Btk_glUniform2f = NULL;
PFNGLUNIFORM2FVPROC Btk_glUniform2fv = NULL;
PFNGLUNIFORM2IPROC Btk_glUniform2i = NULL;
PFNGLUNIFORM2IVPROC Btk_glUniform2iv = NULL;
PFNGLUNIFORM2UIPROC Btk_glUniform2ui = NULL;
PFNGLUNIFORM2UIVPROC Btk_glUniform2uiv = NULL;
PFNGLUNIFORM3FPROC Btk_glUniform3f = NULL;
PFNGLUNIFORM3FVPROC Btk_glUniform3fv = NULL;
PFNGLUNIFORM3IPROC Btk_glUniform3i = NULL;
PFNGLUNIFORM3IVPROC Btk_glUniform3iv = NULL;
PFNGLUNIFORM3UIPROC Btk_glUniform3ui = NULL;
PFNGLUNIFORM3UIVPROC Btk_glUniform3uiv = NULL;
PFNGLUNIFORM4FPROC Btk_glUniform4f = NULL;
PFNGLUNIFORM4FVPROC Btk_glUniform4fv = NULL;
PFNGLUNIFORM4IPROC Btk_glUniform4i = NULL;
PFNGLUNIFORM4IVPROC Btk_glUniform4iv = NULL;
PFNGLUNIFORM4UIPROC Btk_glUniform4ui = NULL;
PFNGLUNIFORM4UIVPROC Btk_glUniform4uiv = NULL;
PFNGLUNIFORMBLOCKBINDINGPROC Btk_glUniformBlockBinding = NULL;
PFNGLUNIFORMMATRIX2FVPROC Btk_glUniformMatrix2fv = NULL;
PFNGLUNIFORMMATRIX2X3FVPROC Btk_glUniformMatrix2x3fv = NULL;
PFNGLUNIFORMMATRIX2X4FVPROC Btk_glUniformMatrix2x4fv = NULL;
PFNGLUNIFORMMATRIX3FVPROC Btk_glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX3X2FVPROC Btk_glUniformMatrix3x2fv = NULL;
PFNGLUNIFORMMATRIX3X4FVPROC Btk_glUniformMatrix3x4fv = NULL;
PFNGLUNIFORMMATRIX4FVPROC Btk_glUniformMatrix4fv = NULL;
PFNGLUNIFORMMATRIX4X2FVPROC Btk_glUniformMatrix4x2fv = NULL;
PFNGLUNIFORMMATRIX4X3FVPROC Btk_glUniformMatrix4x3fv = NULL;
PFNGLUNMAPBUFFERPROC Btk_glUnmapBuffer = NULL;
PFNGLUSEPROGRAMPROC Btk_glUseProgram = NULL;
PFNGLUSEPROGRAMSTAGESPROC Btk_glUseProgramStages = NULL;
PFNGLVALIDATEPROGRAMPROC Btk_glValidateProgram = NULL;
PFNGLVALIDATEPROGRAMPIPELINEPROC Btk_glValidateProgramPipeline = NULL;
PFNGLVERTEXATTRIB1FPROC Btk_glVertexAttrib1f = NULL;
PFNGLVERTEXATTRIB1FVPROC Btk_glVertexAttrib1fv = NULL;
PFNGLVERTEXATTRIB2FPROC Btk_glVertexAttrib2f = NULL;
PFNGLVERTEXATTRIB2FVPROC Btk_glVertexAttrib2fv = NULL;
PFNGLVERTEXATTRIB3FPROC Btk_glVertexAttrib3f = NULL;
PFNGLVERTEXATTRIB3FVPROC Btk_glVertexAttrib3fv = NULL;
PFNGLVERTEXATTRIB4FPROC Btk_glVertexAttrib4f = NULL;
PFNGLVERTEXATTRIB4FVPROC Btk_glVertexAttrib4fv = NULL;
PFNGLVERTEXATTRIBBINDINGPROC Btk_glVertexAttribBinding = NULL;
PFNGLVERTEXATTRIBDIVISORPROC Btk_glVertexAttribDivisor = NULL;
PFNGLVERTEXATTRIBFORMATPROC Btk_glVertexAttribFormat = NULL;
PFNGLVERTEXATTRIBI4IPROC Btk_glVertexAttribI4i = NULL;
PFNGLVERTEXATTRIBI4IVPROC Btk_glVertexAttribI4iv = NULL;
PFNGLVERTEXATTRIBI4UIPROC Btk_glVertexAttribI4ui = NULL;
PFNGLVERTEXATTRIBI4UIVPROC Btk_glVertexAttribI4uiv = NULL;
PFNGLVERTEXATTRIBIFORMATPROC Btk_glVertexAttribIFormat = NULL;
PFNGLVERTEXATTRIBIPOINTERPROC Btk_glVertexAttribIPointer = NULL;
PFNGLVERTEXATTRIBPOINTERPROC Btk_glVertexAttribPointer = NULL;
PFNGLVERTEXBINDINGDIVISORPROC Btk_glVertexBindingDivisor = NULL;
PFNGLVIEWPORTPROC Btk_glViewport = NULL;
PFNGLWAITSYNCPROC Btk_glWaitSync = NULL;
static void load_GL_ES_VERSION_2_0(GLADloadproc load) {
	if(!BTK_GL_ES_VERSION_2_0) return;
	Btk_glActiveTexture = (PFNGLACTIVETEXTUREPROC)load("glActiveTexture");
	Btk_glAttachShader = (PFNGLATTACHSHADERPROC)load("glAttachShader");
	Btk_glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)load("glBindAttribLocation");
	Btk_glBindBuffer = (PFNGLBINDBUFFERPROC)load("glBindBuffer");
	Btk_glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)load("glBindFramebuffer");
	Btk_glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)load("glBindRenderbuffer");
	Btk_glBindTexture = (PFNGLBINDTEXTUREPROC)load("glBindTexture");
	Btk_glBlendColor = (PFNGLBLENDCOLORPROC)load("glBlendColor");
	Btk_glBlendEquation = (PFNGLBLENDEQUATIONPROC)load("glBlendEquation");
	Btk_glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)load("glBlendEquationSeparate");
	Btk_glBlendFunc = (PFNGLBLENDFUNCPROC)load("glBlendFunc");
	Btk_glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC)load("glBlendFuncSeparate");
	Btk_glBufferData = (PFNGLBUFFERDATAPROC)load("glBufferData");
	Btk_glBufferSubData = (PFNGLBUFFERSUBDATAPROC)load("glBufferSubData");
	Btk_glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)load("glCheckFramebufferStatus");
	Btk_glClear = (PFNGLCLEARPROC)load("glClear");
	Btk_glClearColor = (PFNGLCLEARCOLORPROC)load("glClearColor");
	Btk_glClearDepthf = (PFNGLCLEARDEPTHFPROC)load("glClearDepthf");
	Btk_glClearStencil = (PFNGLCLEARSTENCILPROC)load("glClearStencil");
	Btk_glColorMask = (PFNGLCOLORMASKPROC)load("glColorMask");
	Btk_glCompileShader = (PFNGLCOMPILESHADERPROC)load("glCompileShader");
	Btk_glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC)load("glCompressedTexImage2D");
	Btk_glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC)load("glCompressedTexSubImage2D");
	Btk_glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC)load("glCopyTexImage2D");
	Btk_glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC)load("glCopyTexSubImage2D");
	Btk_glCreateProgram = (PFNGLCREATEPROGRAMPROC)load("glCreateProgram");
	Btk_glCreateShader = (PFNGLCREATESHADERPROC)load("glCreateShader");
	Btk_glCullFace = (PFNGLCULLFACEPROC)load("glCullFace");
	Btk_glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)load("glDeleteBuffers");
	Btk_glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)load("glDeleteFramebuffers");
	Btk_glDeleteProgram = (PFNGLDELETEPROGRAMPROC)load("glDeleteProgram");
	Btk_glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)load("glDeleteRenderbuffers");
	Btk_glDeleteShader = (PFNGLDELETESHADERPROC)load("glDeleteShader");
	Btk_glDeleteTextures = (PFNGLDELETETEXTURESPROC)load("glDeleteTextures");
	Btk_glDepthFunc = (PFNGLDEPTHFUNCPROC)load("glDepthFunc");
	Btk_glDepthMask = (PFNGLDEPTHMASKPROC)load("glDepthMask");
	Btk_glDepthRangef = (PFNGLDEPTHRANGEFPROC)load("glDepthRangef");
	Btk_glDetachShader = (PFNGLDETACHSHADERPROC)load("glDetachShader");
	Btk_glDisable = (PFNGLDISABLEPROC)load("glDisable");
	Btk_glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)load("glDisableVertexAttribArray");
	Btk_glDrawArrays = (PFNGLDRAWARRAYSPROC)load("glDrawArrays");
	Btk_glDrawElements = (PFNGLDRAWELEMENTSPROC)load("glDrawElements");
	Btk_glEnable = (PFNGLENABLEPROC)load("glEnable");
	Btk_glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)load("glEnableVertexAttribArray");
	Btk_glFinish = (PFNGLFINISHPROC)load("glFinish");
	Btk_glFlush = (PFNGLFLUSHPROC)load("glFlush");
	Btk_glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)load("glFramebufferRenderbuffer");
	Btk_glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)load("glFramebufferTexture2D");
	Btk_glFrontFace = (PFNGLFRONTFACEPROC)load("glFrontFace");
	Btk_glGenBuffers = (PFNGLGENBUFFERSPROC)load("glGenBuffers");
	Btk_glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)load("glGenerateMipmap");
	Btk_glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)load("glGenFramebuffers");
	Btk_glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)load("glGenRenderbuffers");
	Btk_glGenTextures = (PFNGLGENTEXTURESPROC)load("glGenTextures");
	Btk_glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)load("glGetActiveAttrib");
	Btk_glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)load("glGetActiveUniform");
	Btk_glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)load("glGetAttachedShaders");
	Btk_glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)load("glGetAttribLocation");
	Btk_glGetBooleanv = (PFNGLGETBOOLEANVPROC)load("glGetBooleanv");
	Btk_glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)load("glGetBufferParameteriv");
	Btk_glGetError = (PFNGLGETERRORPROC)load("glGetError");
	Btk_glGetFloatv = (PFNGLGETFLOATVPROC)load("glGetFloatv");
	Btk_glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)load("glGetFramebufferAttachmentParameteriv");
	Btk_glGetIntegerv = (PFNGLGETINTEGERVPROC)load("glGetIntegerv");
	Btk_glGetProgramiv = (PFNGLGETPROGRAMIVPROC)load("glGetProgramiv");
	Btk_glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)load("glGetProgramInfoLog");
	Btk_glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)load("glGetRenderbufferParameteriv");
	Btk_glGetShaderiv = (PFNGLGETSHADERIVPROC)load("glGetShaderiv");
	Btk_glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)load("glGetShaderInfoLog");
	Btk_glGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC)load("glGetShaderPrecisionFormat");
	Btk_glGetShaderSource = (PFNGLGETSHADERSOURCEPROC)load("glGetShaderSource");
	Btk_glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
	Btk_glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC)load("glGetTexParameterfv");
	Btk_glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC)load("glGetTexParameteriv");
	Btk_glGetUniformfv = (PFNGLGETUNIFORMFVPROC)load("glGetUniformfv");
	Btk_glGetUniformiv = (PFNGLGETUNIFORMIVPROC)load("glGetUniformiv");
	Btk_glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)load("glGetUniformLocation");
	Btk_glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC)load("glGetVertexAttribfv");
	Btk_glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC)load("glGetVertexAttribiv");
	Btk_glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC)load("glGetVertexAttribPointerv");
	Btk_glHint = (PFNGLHINTPROC)load("glHint");
	Btk_glIsBuffer = (PFNGLISBUFFERPROC)load("glIsBuffer");
	Btk_glIsEnabled = (PFNGLISENABLEDPROC)load("glIsEnabled");
	Btk_glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)load("glIsFramebuffer");
	Btk_glIsProgram = (PFNGLISPROGRAMPROC)load("glIsProgram");
	Btk_glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)load("glIsRenderbuffer");
	Btk_glIsShader = (PFNGLISSHADERPROC)load("glIsShader");
	Btk_glIsTexture = (PFNGLISTEXTUREPROC)load("glIsTexture");
	Btk_glLineWidth = (PFNGLLINEWIDTHPROC)load("glLineWidth");
	Btk_glLinkProgram = (PFNGLLINKPROGRAMPROC)load("glLinkProgram");
	Btk_glPixelStorei = (PFNGLPIXELSTOREIPROC)load("glPixelStorei");
	Btk_glPolygonOffset = (PFNGLPOLYGONOFFSETPROC)load("glPolygonOffset");
	Btk_glReadPixels = (PFNGLREADPIXELSPROC)load("glReadPixels");
	Btk_glReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC)load("glReleaseShaderCompiler");
	Btk_glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)load("glRenderbufferStorage");
	Btk_glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC)load("glSampleCoverage");
	Btk_glScissor = (PFNGLSCISSORPROC)load("glScissor");
	Btk_glShaderBinary = (PFNGLSHADERBINARYPROC)load("glShaderBinary");
	Btk_glShaderSource = (PFNGLSHADERSOURCEPROC)load("glShaderSource");
	Btk_glStencilFunc = (PFNGLSTENCILFUNCPROC)load("glStencilFunc");
	Btk_glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC)load("glStencilFuncSeparate");
	Btk_glStencilMask = (PFNGLSTENCILMASKPROC)load("glStencilMask");
	Btk_glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC)load("glStencilMaskSeparate");
	Btk_glStencilOp = (PFNGLSTENCILOPPROC)load("glStencilOp");
	Btk_glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC)load("glStencilOpSeparate");
	Btk_glTexImage2D = (PFNGLTEXIMAGE2DPROC)load("glTexImage2D");
	Btk_glTexParameterf = (PFNGLTEXPARAMETERFPROC)load("glTexParameterf");
	Btk_glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)load("glTexParameterfv");
	Btk_glTexParameteri = (PFNGLTEXPARAMETERIPROC)load("glTexParameteri");
	Btk_glTexParameteriv = (PFNGLTEXPARAMETERIVPROC)load("glTexParameteriv");
	Btk_glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)load("glTexSubImage2D");
	Btk_glUniform1f = (PFNGLUNIFORM1FPROC)load("glUniform1f");
	Btk_glUniform1fv = (PFNGLUNIFORM1FVPROC)load("glUniform1fv");
	Btk_glUniform1i = (PFNGLUNIFORM1IPROC)load("glUniform1i");
	Btk_glUniform1iv = (PFNGLUNIFORM1IVPROC)load("glUniform1iv");
	Btk_glUniform2f = (PFNGLUNIFORM2FPROC)load("glUniform2f");
	Btk_glUniform2fv = (PFNGLUNIFORM2FVPROC)load("glUniform2fv");
	Btk_glUniform2i = (PFNGLUNIFORM2IPROC)load("glUniform2i");
	Btk_glUniform2iv = (PFNGLUNIFORM2IVPROC)load("glUniform2iv");
	Btk_glUniform3f = (PFNGLUNIFORM3FPROC)load("glUniform3f");
	Btk_glUniform3fv = (PFNGLUNIFORM3FVPROC)load("glUniform3fv");
	Btk_glUniform3i = (PFNGLUNIFORM3IPROC)load("glUniform3i");
	Btk_glUniform3iv = (PFNGLUNIFORM3IVPROC)load("glUniform3iv");
	Btk_glUniform4f = (PFNGLUNIFORM4FPROC)load("glUniform4f");
	Btk_glUniform4fv = (PFNGLUNIFORM4FVPROC)load("glUniform4fv");
	Btk_glUniform4i = (PFNGLUNIFORM4IPROC)load("glUniform4i");
	Btk_glUniform4iv = (PFNGLUNIFORM4IVPROC)load("glUniform4iv");
	Btk_glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)load("glUniformMatrix2fv");
	Btk_glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)load("glUniformMatrix3fv");
	Btk_glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)load("glUniformMatrix4fv");
	Btk_glUseProgram = (PFNGLUSEPROGRAMPROC)load("glUseProgram");
	Btk_glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)load("glValidateProgram");
	Btk_glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)load("glVertexAttrib1f");
	Btk_glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)load("glVertexAttrib1fv");
	Btk_glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC)load("glVertexAttrib2f");
	Btk_glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC)load("glVertexAttrib2fv");
	Btk_glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC)load("glVertexAttrib3f");
	Btk_glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC)load("glVertexAttrib3fv");
	Btk_glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC)load("glVertexAttrib4f");
	Btk_glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC)load("glVertexAttrib4fv");
	Btk_glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)load("glVertexAttribPointer");
	Btk_glViewport = (PFNGLVIEWPORTPROC)load("glViewport");
}
static void load_GL_ES_VERSION_3_0(GLADloadproc load) {
	if(!BTK_GL_ES_VERSION_3_0) return;
	Btk_glReadBuffer = (PFNGLREADBUFFERPROC)load("glReadBuffer");
	Btk_glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC)load("glDrawRangeElements");
	Btk_glTexImage3D = (PFNGLTEXIMAGE3DPROC)load("glTexImage3D");
	Btk_glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC)load("glTexSubImage3D");
	Btk_glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC)load("glCopyTexSubImage3D");
	Btk_glCompressedTexImage3D = (PFNGLCOMPRESSEDTEXIMAGE3DPROC)load("glCompressedTexImage3D");
	Btk_glCompressedTexSubImage3D = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC)load("glCompressedTexSubImage3D");
	Btk_glGenQueries = (PFNGLGENQUERIESPROC)load("glGenQueries");
	Btk_glDeleteQueries = (PFNGLDELETEQUERIESPROC)load("glDeleteQueries");
	Btk_glIsQuery = (PFNGLISQUERYPROC)load("glIsQuery");
	Btk_glBeginQuery = (PFNGLBEGINQUERYPROC)load("glBeginQuery");
	Btk_glEndQuery = (PFNGLENDQUERYPROC)load("glEndQuery");
	Btk_glGetQueryiv = (PFNGLGETQUERYIVPROC)load("glGetQueryiv");
	Btk_glGetQueryObjectuiv = (PFNGLGETQUERYOBJECTUIVPROC)load("glGetQueryObjectuiv");
	Btk_glUnmapBuffer = (PFNGLUNMAPBUFFERPROC)load("glUnmapBuffer");
	Btk_glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC)load("glGetBufferPointerv");
	Btk_glDrawBuffers = (PFNGLDRAWBUFFERSPROC)load("glDrawBuffers");
	Btk_glUniformMatrix2x3fv = (PFNGLUNIFORMMATRIX2X3FVPROC)load("glUniformMatrix2x3fv");
	Btk_glUniformMatrix3x2fv = (PFNGLUNIFORMMATRIX3X2FVPROC)load("glUniformMatrix3x2fv");
	Btk_glUniformMatrix2x4fv = (PFNGLUNIFORMMATRIX2X4FVPROC)load("glUniformMatrix2x4fv");
	Btk_glUniformMatrix4x2fv = (PFNGLUNIFORMMATRIX4X2FVPROC)load("glUniformMatrix4x2fv");
	Btk_glUniformMatrix3x4fv = (PFNGLUNIFORMMATRIX3X4FVPROC)load("glUniformMatrix3x4fv");
	Btk_glUniformMatrix4x3fv = (PFNGLUNIFORMMATRIX4X3FVPROC)load("glUniformMatrix4x3fv");
	Btk_glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)load("glBlitFramebuffer");
	Btk_glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)load("glRenderbufferStorageMultisample");
	Btk_glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC)load("glFramebufferTextureLayer");
	Btk_glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC)load("glMapBufferRange");
	Btk_glFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC)load("glFlushMappedBufferRange");
	Btk_glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)load("glBindVertexArray");
	Btk_glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)load("glDeleteVertexArrays");
	Btk_glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)load("glGenVertexArrays");
	Btk_glIsVertexArray = (PFNGLISVERTEXARRAYPROC)load("glIsVertexArray");
	Btk_glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC)load("glGetIntegeri_v");
	Btk_glBeginTransformFeedback = (PFNGLBEGINTRANSFORMFEEDBACKPROC)load("glBeginTransformFeedback");
	Btk_glEndTransformFeedback = (PFNGLENDTRANSFORMFEEDBACKPROC)load("glEndTransformFeedback");
	Btk_glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC)load("glBindBufferRange");
	Btk_glBindBufferBase = (PFNGLBINDBUFFERBASEPROC)load("glBindBufferBase");
	Btk_glTransformFeedbackVaryings = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC)load("glTransformFeedbackVaryings");
	Btk_glGetTransformFeedbackVarying = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC)load("glGetTransformFeedbackVarying");
	Btk_glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC)load("glVertexAttribIPointer");
	Btk_glGetVertexAttribIiv = (PFNGLGETVERTEXATTRIBIIVPROC)load("glGetVertexAttribIiv");
	Btk_glGetVertexAttribIuiv = (PFNGLGETVERTEXATTRIBIUIVPROC)load("glGetVertexAttribIuiv");
	Btk_glVertexAttribI4i = (PFNGLVERTEXATTRIBI4IPROC)load("glVertexAttribI4i");
	Btk_glVertexAttribI4ui = (PFNGLVERTEXATTRIBI4UIPROC)load("glVertexAttribI4ui");
	Btk_glVertexAttribI4iv = (PFNGLVERTEXATTRIBI4IVPROC)load("glVertexAttribI4iv");
	Btk_glVertexAttribI4uiv = (PFNGLVERTEXATTRIBI4UIVPROC)load("glVertexAttribI4uiv");
	Btk_glGetUniformuiv = (PFNGLGETUNIFORMUIVPROC)load("glGetUniformuiv");
	Btk_glGetFragDataLocation = (PFNGLGETFRAGDATALOCATIONPROC)load("glGetFragDataLocation");
	Btk_glUniform1ui = (PFNGLUNIFORM1UIPROC)load("glUniform1ui");
	Btk_glUniform2ui = (PFNGLUNIFORM2UIPROC)load("glUniform2ui");
	Btk_glUniform3ui = (PFNGLUNIFORM3UIPROC)load("glUniform3ui");
	Btk_glUniform4ui = (PFNGLUNIFORM4UIPROC)load("glUniform4ui");
	Btk_glUniform1uiv = (PFNGLUNIFORM1UIVPROC)load("glUniform1uiv");
	Btk_glUniform2uiv = (PFNGLUNIFORM2UIVPROC)load("glUniform2uiv");
	Btk_glUniform3uiv = (PFNGLUNIFORM3UIVPROC)load("glUniform3uiv");
	Btk_glUniform4uiv = (PFNGLUNIFORM4UIVPROC)load("glUniform4uiv");
	Btk_glClearBufferiv = (PFNGLCLEARBUFFERIVPROC)load("glClearBufferiv");
	Btk_glClearBufferuiv = (PFNGLCLEARBUFFERUIVPROC)load("glClearBufferuiv");
	Btk_glClearBufferfv = (PFNGLCLEARBUFFERFVPROC)load("glClearBufferfv");
	Btk_glClearBufferfi = (PFNGLCLEARBUFFERFIPROC)load("glClearBufferfi");
	Btk_glGetStringi = (PFNGLGETSTRINGIPROC)load("glGetStringi");
	Btk_glCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC)load("glCopyBufferSubData");
	Btk_glGetUniformIndices = (PFNGLGETUNIFORMINDICESPROC)load("glGetUniformIndices");
	Btk_glGetActiveUniformsiv = (PFNGLGETACTIVEUNIFORMSIVPROC)load("glGetActiveUniformsiv");
	Btk_glGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC)load("glGetUniformBlockIndex");
	Btk_glGetActiveUniformBlockiv = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC)load("glGetActiveUniformBlockiv");
	Btk_glGetActiveUniformBlockName = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC)load("glGetActiveUniformBlockName");
	Btk_glUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC)load("glUniformBlockBinding");
	Btk_glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC)load("glDrawArraysInstanced");
	Btk_glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC)load("glDrawElementsInstanced");
	Btk_glFenceSync = (PFNGLFENCESYNCPROC)load("glFenceSync");
	Btk_glIsSync = (PFNGLISSYNCPROC)load("glIsSync");
	Btk_glDeleteSync = (PFNGLDELETESYNCPROC)load("glDeleteSync");
	Btk_glClientWaitSync = (PFNGLCLIENTWAITSYNCPROC)load("glClientWaitSync");
	Btk_glWaitSync = (PFNGLWAITSYNCPROC)load("glWaitSync");
	Btk_glGetInteger64v = (PFNGLGETINTEGER64VPROC)load("glGetInteger64v");
	Btk_glGetSynciv = (PFNGLGETSYNCIVPROC)load("glGetSynciv");
	Btk_glGetInteger64i_v = (PFNGLGETINTEGER64I_VPROC)load("glGetInteger64i_v");
	Btk_glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC)load("glGetBufferParameteri64v");
	Btk_glGenSamplers = (PFNGLGENSAMPLERSPROC)load("glGenSamplers");
	Btk_glDeleteSamplers = (PFNGLDELETESAMPLERSPROC)load("glDeleteSamplers");
	Btk_glIsSampler = (PFNGLISSAMPLERPROC)load("glIsSampler");
	Btk_glBindSampler = (PFNGLBINDSAMPLERPROC)load("glBindSampler");
	Btk_glSamplerParameteri = (PFNGLSAMPLERPARAMETERIPROC)load("glSamplerParameteri");
	Btk_glSamplerParameteriv = (PFNGLSAMPLERPARAMETERIVPROC)load("glSamplerParameteriv");
	Btk_glSamplerParameterf = (PFNGLSAMPLERPARAMETERFPROC)load("glSamplerParameterf");
	Btk_glSamplerParameterfv = (PFNGLSAMPLERPARAMETERFVPROC)load("glSamplerParameterfv");
	Btk_glGetSamplerParameteriv = (PFNGLGETSAMPLERPARAMETERIVPROC)load("glGetSamplerParameteriv");
	Btk_glGetSamplerParameterfv = (PFNGLGETSAMPLERPARAMETERFVPROC)load("glGetSamplerParameterfv");
	Btk_glVertexAttribDivisor = (PFNGLVERTEXATTRIBDIVISORPROC)load("glVertexAttribDivisor");
	Btk_glBindTransformFeedback = (PFNGLBINDTRANSFORMFEEDBACKPROC)load("glBindTransformFeedback");
	Btk_glDeleteTransformFeedbacks = (PFNGLDELETETRANSFORMFEEDBACKSPROC)load("glDeleteTransformFeedbacks");
	Btk_glGenTransformFeedbacks = (PFNGLGENTRANSFORMFEEDBACKSPROC)load("glGenTransformFeedbacks");
	Btk_glIsTransformFeedback = (PFNGLISTRANSFORMFEEDBACKPROC)load("glIsTransformFeedback");
	Btk_glPauseTransformFeedback = (PFNGLPAUSETRANSFORMFEEDBACKPROC)load("glPauseTransformFeedback");
	Btk_glResumeTransformFeedback = (PFNGLRESUMETRANSFORMFEEDBACKPROC)load("glResumeTransformFeedback");
	Btk_glGetProgramBinary = (PFNGLGETPROGRAMBINARYPROC)load("glGetProgramBinary");
	Btk_glProgramBinary = (PFNGLPROGRAMBINARYPROC)load("glProgramBinary");
	Btk_glProgramParameteri = (PFNGLPROGRAMPARAMETERIPROC)load("glProgramParameteri");
	Btk_glInvalidateFramebuffer = (PFNGLINVALIDATEFRAMEBUFFERPROC)load("glInvalidateFramebuffer");
	Btk_glInvalidateSubFramebuffer = (PFNGLINVALIDATESUBFRAMEBUFFERPROC)load("glInvalidateSubFramebuffer");
	Btk_glTexStorage2D = (PFNGLTEXSTORAGE2DPROC)load("glTexStorage2D");
	Btk_glTexStorage3D = (PFNGLTEXSTORAGE3DPROC)load("glTexStorage3D");
	Btk_glGetInternalformativ = (PFNGLGETINTERNALFORMATIVPROC)load("glGetInternalformativ");
}
static void load_GL_ES_VERSION_3_1(GLADloadproc load) {
	if(!BTK_GL_ES_VERSION_3_1) return;
	Btk_glDispatchCompute = (PFNGLDISPATCHCOMPUTEPROC)load("glDispatchCompute");
	Btk_glDispatchComputeIndirect = (PFNGLDISPATCHCOMPUTEINDIRECTPROC)load("glDispatchComputeIndirect");
	Btk_glDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC)load("glDrawArraysIndirect");
	Btk_glDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC)load("glDrawElementsIndirect");
	Btk_glFramebufferParameteri = (PFNGLFRAMEBUFFERPARAMETERIPROC)load("glFramebufferParameteri");
	Btk_glGetFramebufferParameteriv = (PFNGLGETFRAMEBUFFERPARAMETERIVPROC)load("glGetFramebufferParameteriv");
	Btk_glGetProgramInterfaceiv = (PFNGLGETPROGRAMINTERFACEIVPROC)load("glGetProgramInterfaceiv");
	Btk_glGetProgramResourceIndex = (PFNGLGETPROGRAMRESOURCEINDEXPROC)load("glGetProgramResourceIndex");
	Btk_glGetProgramResourceName = (PFNGLGETPROGRAMRESOURCENAMEPROC)load("glGetProgramResourceName");
	Btk_glGetProgramResourceiv = (PFNGLGETPROGRAMRESOURCEIVPROC)load("glGetProgramResourceiv");
	Btk_glGetProgramResourceLocation = (PFNGLGETPROGRAMRESOURCELOCATIONPROC)load("glGetProgramResourceLocation");
	Btk_glUseProgramStages = (PFNGLUSEPROGRAMSTAGESPROC)load("glUseProgramStages");
	Btk_glActiveShaderProgram = (PFNGLACTIVESHADERPROGRAMPROC)load("glActiveShaderProgram");
	Btk_glCreateShaderProgramv = (PFNGLCREATESHADERPROGRAMVPROC)load("glCreateShaderProgramv");
	Btk_glBindProgramPipeline = (PFNGLBINDPROGRAMPIPELINEPROC)load("glBindProgramPipeline");
	Btk_glDeleteProgramPipelines = (PFNGLDELETEPROGRAMPIPELINESPROC)load("glDeleteProgramPipelines");
	Btk_glGenProgramPipelines = (PFNGLGENPROGRAMPIPELINESPROC)load("glGenProgramPipelines");
	Btk_glIsProgramPipeline = (PFNGLISPROGRAMPIPELINEPROC)load("glIsProgramPipeline");
	Btk_glGetProgramPipelineiv = (PFNGLGETPROGRAMPIPELINEIVPROC)load("glGetProgramPipelineiv");
	Btk_glProgramUniform1i = (PFNGLPROGRAMUNIFORM1IPROC)load("glProgramUniform1i");
	Btk_glProgramUniform2i = (PFNGLPROGRAMUNIFORM2IPROC)load("glProgramUniform2i");
	Btk_glProgramUniform3i = (PFNGLPROGRAMUNIFORM3IPROC)load("glProgramUniform3i");
	Btk_glProgramUniform4i = (PFNGLPROGRAMUNIFORM4IPROC)load("glProgramUniform4i");
	Btk_glProgramUniform1ui = (PFNGLPROGRAMUNIFORM1UIPROC)load("glProgramUniform1ui");
	Btk_glProgramUniform2ui = (PFNGLPROGRAMUNIFORM2UIPROC)load("glProgramUniform2ui");
	Btk_glProgramUniform3ui = (PFNGLPROGRAMUNIFORM3UIPROC)load("glProgramUniform3ui");
	Btk_glProgramUniform4ui = (PFNGLPROGRAMUNIFORM4UIPROC)load("glProgramUniform4ui");
	Btk_glProgramUniform1f = (PFNGLPROGRAMUNIFORM1FPROC)load("glProgramUniform1f");
	Btk_glProgramUniform2f = (PFNGLPROGRAMUNIFORM2FPROC)load("glProgramUniform2f");
	Btk_glProgramUniform3f = (PFNGLPROGRAMUNIFORM3FPROC)load("glProgramUniform3f");
	Btk_glProgramUniform4f = (PFNGLPROGRAMUNIFORM4FPROC)load("glProgramUniform4f");
	Btk_glProgramUniform1iv = (PFNGLPROGRAMUNIFORM1IVPROC)load("glProgramUniform1iv");
	Btk_glProgramUniform2iv = (PFNGLPROGRAMUNIFORM2IVPROC)load("glProgramUniform2iv");
	Btk_glProgramUniform3iv = (PFNGLPROGRAMUNIFORM3IVPROC)load("glProgramUniform3iv");
	Btk_glProgramUniform4iv = (PFNGLPROGRAMUNIFORM4IVPROC)load("glProgramUniform4iv");
	Btk_glProgramUniform1uiv = (PFNGLPROGRAMUNIFORM1UIVPROC)load("glProgramUniform1uiv");
	Btk_glProgramUniform2uiv = (PFNGLPROGRAMUNIFORM2UIVPROC)load("glProgramUniform2uiv");
	Btk_glProgramUniform3uiv = (PFNGLPROGRAMUNIFORM3UIVPROC)load("glProgramUniform3uiv");
	Btk_glProgramUniform4uiv = (PFNGLPROGRAMUNIFORM4UIVPROC)load("glProgramUniform4uiv");
	Btk_glProgramUniform1fv = (PFNGLPROGRAMUNIFORM1FVPROC)load("glProgramUniform1fv");
	Btk_glProgramUniform2fv = (PFNGLPROGRAMUNIFORM2FVPROC)load("glProgramUniform2fv");
	Btk_glProgramUniform3fv = (PFNGLPROGRAMUNIFORM3FVPROC)load("glProgramUniform3fv");
	Btk_glProgramUniform4fv = (PFNGLPROGRAMUNIFORM4FVPROC)load("glProgramUniform4fv");
	Btk_glProgramUniformMatrix2fv = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC)load("glProgramUniformMatrix2fv");
	Btk_glProgramUniformMatrix3fv = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC)load("glProgramUniformMatrix3fv");
	Btk_glProgramUniformMatrix4fv = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC)load("glProgramUniformMatrix4fv");
	Btk_glProgramUniformMatrix2x3fv = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC)load("glProgramUniformMatrix2x3fv");
	Btk_glProgramUniformMatrix3x2fv = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC)load("glProgramUniformMatrix3x2fv");
	Btk_glProgramUniformMatrix2x4fv = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC)load("glProgramUniformMatrix2x4fv");
	Btk_glProgramUniformMatrix4x2fv = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC)load("glProgramUniformMatrix4x2fv");
	Btk_glProgramUniformMatrix3x4fv = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC)load("glProgramUniformMatrix3x4fv");
	Btk_glProgramUniformMatrix4x3fv = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC)load("glProgramUniformMatrix4x3fv");
	Btk_glValidateProgramPipeline = (PFNGLVALIDATEPROGRAMPIPELINEPROC)load("glValidateProgramPipeline");
	Btk_glGetProgramPipelineInfoLog = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC)load("glGetProgramPipelineInfoLog");
	Btk_glBindImageTexture = (PFNGLBINDIMAGETEXTUREPROC)load("glBindImageTexture");
	Btk_glGetBooleani_v = (PFNGLGETBOOLEANI_VPROC)load("glGetBooleani_v");
	Btk_glMemoryBarrier = (PFNGLMEMORYBARRIERPROC)load("glMemoryBarrier");
	Btk_glMemoryBarrierByRegion = (PFNGLMEMORYBARRIERBYREGIONPROC)load("glMemoryBarrierByRegion");
	Btk_glTexStorage2DMultisample = (PFNGLTEXSTORAGE2DMULTISAMPLEPROC)load("glTexStorage2DMultisample");
	Btk_glGetMultisamplefv = (PFNGLGETMULTISAMPLEFVPROC)load("glGetMultisamplefv");
	Btk_glSampleMaski = (PFNGLSAMPLEMASKIPROC)load("glSampleMaski");
	Btk_glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC)load("glGetTexLevelParameteriv");
	Btk_glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC)load("glGetTexLevelParameterfv");
	Btk_glBindVertexBuffer = (PFNGLBINDVERTEXBUFFERPROC)load("glBindVertexBuffer");
	Btk_glVertexAttribFormat = (PFNGLVERTEXATTRIBFORMATPROC)load("glVertexAttribFormat");
	Btk_glVertexAttribIFormat = (PFNGLVERTEXATTRIBIFORMATPROC)load("glVertexAttribIFormat");
	Btk_glVertexAttribBinding = (PFNGLVERTEXATTRIBBINDINGPROC)load("glVertexAttribBinding");
	Btk_glVertexBindingDivisor = (PFNGLVERTEXBINDINGDIVISORPROC)load("glVertexBindingDivisor");
}
static void load_GL_ES_VERSION_3_2(GLADloadproc load) {
	if(!BTK_GL_ES_VERSION_3_2) return;
	Btk_glBlendBarrier = (PFNGLBLENDBARRIERPROC)load("glBlendBarrier");
	Btk_glCopyImageSubData = (PFNGLCOPYIMAGESUBDATAPROC)load("glCopyImageSubData");
	Btk_glDebugMessageControl = (PFNGLDEBUGMESSAGECONTROLPROC)load("glDebugMessageControl");
	Btk_glDebugMessageInsert = (PFNGLDEBUGMESSAGEINSERTPROC)load("glDebugMessageInsert");
	Btk_glDebugMessageCallback = (PFNGLDEBUGMESSAGECALLBACKPROC)load("glDebugMessageCallback");
	Btk_glGetDebugMessageLog = (PFNGLGETDEBUGMESSAGELOGPROC)load("glGetDebugMessageLog");
	Btk_glPushDebugGroup = (PFNGLPUSHDEBUGGROUPPROC)load("glPushDebugGroup");
	Btk_glPopDebugGroup = (PFNGLPOPDEBUGGROUPPROC)load("glPopDebugGroup");
	Btk_glObjectLabel = (PFNGLOBJECTLABELPROC)load("glObjectLabel");
	Btk_glGetObjectLabel = (PFNGLGETOBJECTLABELPROC)load("glGetObjectLabel");
	Btk_glObjectPtrLabel = (PFNGLOBJECTPTRLABELPROC)load("glObjectPtrLabel");
	Btk_glGetObjectPtrLabel = (PFNGLGETOBJECTPTRLABELPROC)load("glGetObjectPtrLabel");
	Btk_glGetPointerv = (PFNGLGETPOINTERVPROC)load("glGetPointerv");
	Btk_glEnablei = (PFNGLENABLEIPROC)load("glEnablei");
	Btk_glDisablei = (PFNGLDISABLEIPROC)load("glDisablei");
	Btk_glBlendEquationi = (PFNGLBLENDEQUATIONIPROC)load("glBlendEquationi");
	Btk_glBlendEquationSeparatei = (PFNGLBLENDEQUATIONSEPARATEIPROC)load("glBlendEquationSeparatei");
	Btk_glBlendFunci = (PFNGLBLENDFUNCIPROC)load("glBlendFunci");
	Btk_glBlendFuncSeparatei = (PFNGLBLENDFUNCSEPARATEIPROC)load("glBlendFuncSeparatei");
	Btk_glColorMaski = (PFNGLCOLORMASKIPROC)load("glColorMaski");
	Btk_glIsEnabledi = (PFNGLISENABLEDIPROC)load("glIsEnabledi");
	Btk_glDrawElementsBaseVertex = (PFNGLDRAWELEMENTSBASEVERTEXPROC)load("glDrawElementsBaseVertex");
	Btk_glDrawRangeElementsBaseVertex = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC)load("glDrawRangeElementsBaseVertex");
	Btk_glDrawElementsInstancedBaseVertex = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC)load("glDrawElementsInstancedBaseVertex");
	Btk_glFramebufferTexture = (PFNGLFRAMEBUFFERTEXTUREPROC)load("glFramebufferTexture");
	Btk_glPrimitiveBoundingBox = (PFNGLPRIMITIVEBOUNDINGBOXPROC)load("glPrimitiveBoundingBox");
	Btk_glGetGraphicsResetStatus = (PFNGLGETGRAPHICSRESETSTATUSPROC)load("glGetGraphicsResetStatus");
	Btk_glReadnPixels = (PFNGLREADNPIXELSPROC)load("glReadnPixels");
	Btk_glGetnUniformfv = (PFNGLGETNUNIFORMFVPROC)load("glGetnUniformfv");
	Btk_glGetnUniformiv = (PFNGLGETNUNIFORMIVPROC)load("glGetnUniformiv");
	Btk_glGetnUniformuiv = (PFNGLGETNUNIFORMUIVPROC)load("glGetnUniformuiv");
	Btk_glMinSampleShading = (PFNGLMINSAMPLESHADINGPROC)load("glMinSampleShading");
	Btk_glPatchParameteri = (PFNGLPATCHPARAMETERIPROC)load("glPatchParameteri");
	Btk_glTexParameterIiv = (PFNGLTEXPARAMETERIIVPROC)load("glTexParameterIiv");
	Btk_glTexParameterIuiv = (PFNGLTEXPARAMETERIUIVPROC)load("glTexParameterIuiv");
	Btk_glGetTexParameterIiv = (PFNGLGETTEXPARAMETERIIVPROC)load("glGetTexParameterIiv");
	Btk_glGetTexParameterIuiv = (PFNGLGETTEXPARAMETERIUIVPROC)load("glGetTexParameterIuiv");
	Btk_glSamplerParameterIiv = (PFNGLSAMPLERPARAMETERIIVPROC)load("glSamplerParameterIiv");
	Btk_glSamplerParameterIuiv = (PFNGLSAMPLERPARAMETERIUIVPROC)load("glSamplerParameterIuiv");
	Btk_glGetSamplerParameterIiv = (PFNGLGETSAMPLERPARAMETERIIVPROC)load("glGetSamplerParameterIiv");
	Btk_glGetSamplerParameterIuiv = (PFNGLGETSAMPLERPARAMETERIUIVPROC)load("glGetSamplerParameterIuiv");
	Btk_glTexBuffer = (PFNGLTEXBUFFERPROC)load("glTexBuffer");
	Btk_glTexBufferRange = (PFNGLTEXBUFFERRANGEPROC)load("glTexBufferRange");
	Btk_glTexStorage3DMultisample = (PFNGLTEXSTORAGE3DMULTISAMPLEPROC)load("glTexStorage3DMultisample");
}
static int find_extensionsGLES2(void) {
	if (!get_exts()) return 0;
	(void)&has_ext;
	free_exts();
	return 1;
}

static void find_coreGLES2(void) {

    /* Thank you @elmindreda
     * https://github.com/elmindreda/greg/blob/master/templates/greg.c.in#L176
     * https://github.com/glfw/glfw/blob/master/src/context.c#L36
     */
    int i, major, minor;

    const char* version;
    const char* prefixes[] = {
        "OpenGL ES-CM ",
        "OpenGL ES-CL ",
        "OpenGL ES ",
        NULL
    };

    version = (const char*) glGetString(GL_VERSION);
    if (!version) return;

    for (i = 0;  prefixes[i];  i++) {
        const size_t length = strlen(prefixes[i]);
        if (strncmp(version, prefixes[i], length) == 0) {
            version += length;
            break;
        }
    }

/* PR #18 */
#ifdef _MSC_VER
    sscanf_s(version, "%d.%d", &major, &minor);
#else
    sscanf(version, "%d.%d", &major, &minor);
#endif

    GLVersion.major = major; GLVersion.minor = minor;
    max_loaded_major = major; max_loaded_minor = minor;
	BTK_GL_ES_VERSION_2_0 = (major == 2 && minor >= 0) || major > 2;
	BTK_GL_ES_VERSION_3_0 = (major == 3 && minor >= 0) || major > 3;
	BTK_GL_ES_VERSION_3_1 = (major == 3 && minor >= 1) || major > 3;
	BTK_GL_ES_VERSION_3_2 = (major == 3 && minor >= 2) || major > 3;
	if (GLVersion.major > 3 || (GLVersion.major >= 3 && GLVersion.minor >= 2)) {
		max_loaded_major = 3;
		max_loaded_minor = 2;
	}
}

int BtkLoadGLES2Loader(GLADloadproc load) {
	GLVersion.major = 0; GLVersion.minor = 0;
	glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
	if(glGetString == NULL) return 0;
	if(glGetString(GL_VERSION) == NULL) return 0;
	find_coreGLES2();
	load_GL_ES_VERSION_2_0(load);
	load_GL_ES_VERSION_3_0(load);
	load_GL_ES_VERSION_3_1(load);
	load_GL_ES_VERSION_3_2(load);

	if (!find_extensionsGLES2()) return 0;
	return GLVersion.major != 0 || GLVersion.minor != 0;
}

