/*

    OpenGL ES loader generated by glad 0.1.34 on Thu Feb 18 15:01:57 2021.

    Language/Generator: C/C++
    Specification: gl
    APIs: gles2=2.0
    Profile: compatibility
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="compatibility" --api="gles2=2.0" --generator="c" --spec="gl" --extensions=""
    Online:
        https://glad.dav1d.de/#profile=compatibility&language=c&specification=gl&loader=on&api=gles2%3D2.0
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <Btk/gl/glad.h>

struct gladGLversionStruct GLVersion = { 0, 0 };

#if defined(GL_ES_VERSION_3_0) || defined(GL_VERSION_3_0)
#define _GLAD_IS_SOME_NEW_VERSION 1
#endif

static int max_loaded_major;
static int max_loaded_minor;

static const char *exts = NULL;
static int num_exts_i = 0;
static char **exts_i = NULL;

static int get_exts(void) {
#ifdef _GLAD_IS_SOME_NEW_VERSION
    if(max_loaded_major < 3) {
#endif
        exts = (const char *)glGetString(GL_EXTENSIONS);
#ifdef _GLAD_IS_SOME_NEW_VERSION
    } else {
        unsigned int index;

        num_exts_i = 0;
        glGetIntegerv(GL_NUM_EXTENSIONS, &num_exts_i);
        if (num_exts_i > 0) {
            exts_i = (char **)malloc((size_t)num_exts_i * (sizeof *exts_i));
        }

        if (exts_i == NULL) {
            return 0;
        }

        for(index = 0; index < (unsigned)num_exts_i; index++) {
            const char *gl_str_tmp = (const char*)glGetStringi(GL_EXTENSIONS, index);
            size_t len = strlen(gl_str_tmp);

            char *local_str = (char*)malloc((len+1) * sizeof(char));
            if(local_str != NULL) {
                memcpy(local_str, gl_str_tmp, (len+1) * sizeof(char));
            }
            exts_i[index] = local_str;
        }
    }
#endif
    return 1;
}

static void free_exts(void) {
    if (exts_i != NULL) {
        int index;
        for(index = 0; index < num_exts_i; index++) {
            free((char *)exts_i[index]);
        }
        free((void *)exts_i);
        exts_i = NULL;
    }
}

static int has_ext(const char *ext) {
#ifdef _GLAD_IS_SOME_NEW_VERSION
    if(max_loaded_major < 3) {
#endif
        const char *extensions;
        const char *loc;
        const char *terminator;
        extensions = exts;
        if(extensions == NULL || ext == NULL) {
            return 0;
        }

        while(1) {
            loc = strstr(extensions, ext);
            if(loc == NULL) {
                return 0;
            }

            terminator = loc + strlen(ext);
            if((loc == extensions || *(loc - 1) == ' ') &&
                (*terminator == ' ' || *terminator == '\0')) {
                return 1;
            }
            extensions = terminator;
        }
#ifdef _GLAD_IS_SOME_NEW_VERSION
    } else {
        int index;
        if(exts_i == NULL) return 0;
        for(index = 0; index < num_exts_i; index++) {
            const char *e = exts_i[index];

            if(exts_i[index] != NULL && strcmp(e, ext) == 0) {
                return 1;
            }
        }
    }
#endif

    return 0;
}
int GLAD_GL_ES_VERSION_2_0 = 0;
PFNGLACTIVETEXTUREPROC Btk_glActiveTexture = NULL;
PFNGLATTACHSHADERPROC Btk_glAttachShader = NULL;
PFNGLBINDATTRIBLOCATIONPROC Btk_glBindAttribLocation = NULL;
PFNGLBINDBUFFERPROC Btk_glBindBuffer = NULL;
PFNGLBINDFRAMEBUFFERPROC Btk_glBindFramebuffer = NULL;
PFNGLBINDRENDERBUFFERPROC Btk_glBindRenderbuffer = NULL;
PFNGLBINDTEXTUREPROC Btk_glBindTexture = NULL;
PFNGLBLENDCOLORPROC Btk_glBlendColor = NULL;
PFNGLBLENDEQUATIONPROC Btk_glBlendEquation = NULL;
PFNGLBLENDEQUATIONSEPARATEPROC Btk_glBlendEquationSeparate = NULL;
PFNGLBLENDFUNCPROC Btk_glBlendFunc = NULL;
PFNGLBLENDFUNCSEPARATEPROC Btk_glBlendFuncSeparate = NULL;
PFNGLBUFFERDATAPROC Btk_glBufferData = NULL;
PFNGLBUFFERSUBDATAPROC Btk_glBufferSubData = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC Btk_glCheckFramebufferStatus = NULL;
PFNGLCLEARPROC Btk_glClear = NULL;
PFNGLCLEARCOLORPROC Btk_glClearColor = NULL;
PFNGLCLEARDEPTHFPROC Btk_glClearDepthf = NULL;
PFNGLCLEARSTENCILPROC Btk_glClearStencil = NULL;
PFNGLCOLORMASKPROC Btk_glColorMask = NULL;
PFNGLCOMPILESHADERPROC Btk_glCompileShader = NULL;
PFNGLCOMPRESSEDTEXIMAGE2DPROC Btk_glCompressedTexImage2D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC Btk_glCompressedTexSubImage2D = NULL;
PFNGLCOPYTEXIMAGE2DPROC Btk_glCopyTexImage2D = NULL;
PFNGLCOPYTEXSUBIMAGE2DPROC Btk_glCopyTexSubImage2D = NULL;
PFNGLCREATEPROGRAMPROC Btk_glCreateProgram = NULL;
PFNGLCREATESHADERPROC Btk_glCreateShader = NULL;
PFNGLCULLFACEPROC Btk_glCullFace = NULL;
PFNGLDELETEBUFFERSPROC Btk_glDeleteBuffers = NULL;
PFNGLDELETEFRAMEBUFFERSPROC Btk_glDeleteFramebuffers = NULL;
PFNGLDELETEPROGRAMPROC Btk_glDeleteProgram = NULL;
PFNGLDELETERENDERBUFFERSPROC Btk_glDeleteRenderbuffers = NULL;
PFNGLDELETESHADERPROC Btk_glDeleteShader = NULL;
PFNGLDELETETEXTURESPROC Btk_glDeleteTextures = NULL;
PFNGLDEPTHFUNCPROC Btk_glDepthFunc = NULL;
PFNGLDEPTHMASKPROC Btk_glDepthMask = NULL;
PFNGLDEPTHRANGEFPROC Btk_glDepthRangef = NULL;
PFNGLDETACHSHADERPROC Btk_glDetachShader = NULL;
PFNGLDISABLEPROC Btk_glDisable = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC Btk_glDisableVertexAttribArray = NULL;
PFNGLDRAWARRAYSPROC Btk_glDrawArrays = NULL;
PFNGLDRAWELEMENTSPROC Btk_glDrawElements = NULL;
PFNGLENABLEPROC Btk_glEnable = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC Btk_glEnableVertexAttribArray = NULL;
PFNGLFINISHPROC Btk_glFinish = NULL;
PFNGLFLUSHPROC Btk_glFlush = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC Btk_glFramebufferRenderbuffer = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC Btk_glFramebufferTexture2D = NULL;
PFNGLFRONTFACEPROC Btk_glFrontFace = NULL;
PFNGLGENBUFFERSPROC Btk_glGenBuffers = NULL;
PFNGLGENFRAMEBUFFERSPROC Btk_glGenFramebuffers = NULL;
PFNGLGENRENDERBUFFERSPROC Btk_glGenRenderbuffers = NULL;
PFNGLGENTEXTURESPROC Btk_glGenTextures = NULL;
PFNGLGENERATEMIPMAPPROC Btk_glGenerateMipmap = NULL;
PFNGLGETACTIVEATTRIBPROC Btk_glGetActiveAttrib = NULL;
PFNGLGETACTIVEUNIFORMPROC Btk_glGetActiveUniform = NULL;
PFNGLGETATTACHEDSHADERSPROC Btk_glGetAttachedShaders = NULL;
PFNGLGETATTRIBLOCATIONPROC Btk_glGetAttribLocation = NULL;
PFNGLGETBOOLEANVPROC Btk_glGetBooleanv = NULL;
PFNGLGETBUFFERPARAMETERIVPROC Btk_glGetBufferParameteriv = NULL;
PFNGLGETERRORPROC Btk_glGetError = NULL;
PFNGLGETFLOATVPROC Btk_glGetFloatv = NULL;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC Btk_glGetFramebufferAttachmentParameteriv = NULL;
PFNGLGETINTEGERVPROC Btk_glGetIntegerv = NULL;
PFNGLGETPROGRAMINFOLOGPROC Btk_glGetProgramInfoLog = NULL;
PFNGLGETPROGRAMIVPROC Btk_glGetProgramiv = NULL;
PFNGLGETRENDERBUFFERPARAMETERIVPROC Btk_glGetRenderbufferParameteriv = NULL;
PFNGLGETSHADERINFOLOGPROC Btk_glGetShaderInfoLog = NULL;
PFNGLGETSHADERPRECISIONFORMATPROC Btk_glGetShaderPrecisionFormat = NULL;
PFNGLGETSHADERSOURCEPROC Btk_glGetShaderSource = NULL;
PFNGLGETSHADERIVPROC Btk_glGetShaderiv = NULL;
PFNGLGETSTRINGPROC Btk_glGetString = NULL;
PFNGLGETTEXPARAMETERFVPROC Btk_glGetTexParameterfv = NULL;
PFNGLGETTEXPARAMETERIVPROC Btk_glGetTexParameteriv = NULL;
PFNGLGETUNIFORMLOCATIONPROC Btk_glGetUniformLocation = NULL;
PFNGLGETUNIFORMFVPROC Btk_glGetUniformfv = NULL;
PFNGLGETUNIFORMIVPROC Btk_glGetUniformiv = NULL;
PFNGLGETVERTEXATTRIBPOINTERVPROC Btk_glGetVertexAttribPointerv = NULL;
PFNGLGETVERTEXATTRIBFVPROC Btk_glGetVertexAttribfv = NULL;
PFNGLGETVERTEXATTRIBIVPROC Btk_glGetVertexAttribiv = NULL;
PFNGLHINTPROC Btk_glHint = NULL;
PFNGLISBUFFERPROC Btk_glIsBuffer = NULL;
PFNGLISENABLEDPROC Btk_glIsEnabled = NULL;
PFNGLISFRAMEBUFFERPROC Btk_glIsFramebuffer = NULL;
PFNGLISPROGRAMPROC Btk_glIsProgram = NULL;
PFNGLISRENDERBUFFERPROC Btk_glIsRenderbuffer = NULL;
PFNGLISSHADERPROC Btk_glIsShader = NULL;
PFNGLISTEXTUREPROC Btk_glIsTexture = NULL;
PFNGLLINEWIDTHPROC Btk_glLineWidth = NULL;
PFNGLLINKPROGRAMPROC Btk_glLinkProgram = NULL;
PFNGLPIXELSTOREIPROC Btk_glPixelStorei = NULL;
PFNGLPOLYGONOFFSETPROC Btk_glPolygonOffset = NULL;
PFNGLREADPIXELSPROC Btk_glReadPixels = NULL;
PFNGLRELEASESHADERCOMPILERPROC Btk_glReleaseShaderCompiler = NULL;
PFNGLRENDERBUFFERSTORAGEPROC Btk_glRenderbufferStorage = NULL;
PFNGLSAMPLECOVERAGEPROC Btk_glSampleCoverage = NULL;
PFNGLSCISSORPROC Btk_glScissor = NULL;
PFNGLSHADERBINARYPROC Btk_glShaderBinary = NULL;
PFNGLSHADERSOURCEPROC Btk_glShaderSource = NULL;
PFNGLSTENCILFUNCPROC Btk_glStencilFunc = NULL;
PFNGLSTENCILFUNCSEPARATEPROC Btk_glStencilFuncSeparate = NULL;
PFNGLSTENCILMASKPROC Btk_glStencilMask = NULL;
PFNGLSTENCILMASKSEPARATEPROC Btk_glStencilMaskSeparate = NULL;
PFNGLSTENCILOPPROC Btk_glStencilOp = NULL;
PFNGLSTENCILOPSEPARATEPROC Btk_glStencilOpSeparate = NULL;
PFNGLTEXIMAGE2DPROC Btk_glTexImage2D = NULL;
PFNGLTEXPARAMETERFPROC Btk_glTexParameterf = NULL;
PFNGLTEXPARAMETERFVPROC Btk_glTexParameterfv = NULL;
PFNGLTEXPARAMETERIPROC Btk_glTexParameteri = NULL;
PFNGLTEXPARAMETERIVPROC Btk_glTexParameteriv = NULL;
PFNGLTEXSUBIMAGE2DPROC Btk_glTexSubImage2D = NULL;
PFNGLUNIFORM1FPROC Btk_glUniform1f = NULL;
PFNGLUNIFORM1FVPROC Btk_glUniform1fv = NULL;
PFNGLUNIFORM1IPROC Btk_glUniform1i = NULL;
PFNGLUNIFORM1IVPROC Btk_glUniform1iv = NULL;
PFNGLUNIFORM2FPROC Btk_glUniform2f = NULL;
PFNGLUNIFORM2FVPROC Btk_glUniform2fv = NULL;
PFNGLUNIFORM2IPROC Btk_glUniform2i = NULL;
PFNGLUNIFORM2IVPROC Btk_glUniform2iv = NULL;
PFNGLUNIFORM3FPROC Btk_glUniform3f = NULL;
PFNGLUNIFORM3FVPROC Btk_glUniform3fv = NULL;
PFNGLUNIFORM3IPROC Btk_glUniform3i = NULL;
PFNGLUNIFORM3IVPROC Btk_glUniform3iv = NULL;
PFNGLUNIFORM4FPROC Btk_glUniform4f = NULL;
PFNGLUNIFORM4FVPROC Btk_glUniform4fv = NULL;
PFNGLUNIFORM4IPROC Btk_glUniform4i = NULL;
PFNGLUNIFORM4IVPROC Btk_glUniform4iv = NULL;
PFNGLUNIFORMMATRIX2FVPROC Btk_glUniformMatrix2fv = NULL;
PFNGLUNIFORMMATRIX3FVPROC Btk_glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX4FVPROC Btk_glUniformMatrix4fv = NULL;
PFNGLUSEPROGRAMPROC Btk_glUseProgram = NULL;
PFNGLVALIDATEPROGRAMPROC Btk_glValidateProgram = NULL;
PFNGLVERTEXATTRIB1FPROC Btk_glVertexAttrib1f = NULL;
PFNGLVERTEXATTRIB1FVPROC Btk_glVertexAttrib1fv = NULL;
PFNGLVERTEXATTRIB2FPROC Btk_glVertexAttrib2f = NULL;
PFNGLVERTEXATTRIB2FVPROC Btk_glVertexAttrib2fv = NULL;
PFNGLVERTEXATTRIB3FPROC Btk_glVertexAttrib3f = NULL;
PFNGLVERTEXATTRIB3FVPROC Btk_glVertexAttrib3fv = NULL;
PFNGLVERTEXATTRIB4FPROC Btk_glVertexAttrib4f = NULL;
PFNGLVERTEXATTRIB4FVPROC Btk_glVertexAttrib4fv = NULL;
PFNGLVERTEXATTRIBPOINTERPROC Btk_glVertexAttribPointer = NULL;
PFNGLVIEWPORTPROC Btk_glViewport = NULL;
static void load_GL_ES_VERSION_2_0(GLADloadproc load) {
	if(!GLAD_GL_ES_VERSION_2_0) return;
	Btk_glActiveTexture = (PFNGLACTIVETEXTUREPROC)load("glActiveTexture");
	Btk_glAttachShader = (PFNGLATTACHSHADERPROC)load("glAttachShader");
	Btk_glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)load("glBindAttribLocation");
	Btk_glBindBuffer = (PFNGLBINDBUFFERPROC)load("glBindBuffer");
	Btk_glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)load("glBindFramebuffer");
	Btk_glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)load("glBindRenderbuffer");
	Btk_glBindTexture = (PFNGLBINDTEXTUREPROC)load("glBindTexture");
	Btk_glBlendColor = (PFNGLBLENDCOLORPROC)load("glBlendColor");
	Btk_glBlendEquation = (PFNGLBLENDEQUATIONPROC)load("glBlendEquation");
	Btk_glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)load("glBlendEquationSeparate");
	Btk_glBlendFunc = (PFNGLBLENDFUNCPROC)load("glBlendFunc");
	Btk_glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC)load("glBlendFuncSeparate");
	Btk_glBufferData = (PFNGLBUFFERDATAPROC)load("glBufferData");
	Btk_glBufferSubData = (PFNGLBUFFERSUBDATAPROC)load("glBufferSubData");
	Btk_glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)load("glCheckFramebufferStatus");
	Btk_glClear = (PFNGLCLEARPROC)load("glClear");
	Btk_glClearColor = (PFNGLCLEARCOLORPROC)load("glClearColor");
	Btk_glClearDepthf = (PFNGLCLEARDEPTHFPROC)load("glClearDepthf");
	Btk_glClearStencil = (PFNGLCLEARSTENCILPROC)load("glClearStencil");
	Btk_glColorMask = (PFNGLCOLORMASKPROC)load("glColorMask");
	Btk_glCompileShader = (PFNGLCOMPILESHADERPROC)load("glCompileShader");
	Btk_glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC)load("glCompressedTexImage2D");
	Btk_glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC)load("glCompressedTexSubImage2D");
	Btk_glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC)load("glCopyTexImage2D");
	Btk_glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC)load("glCopyTexSubImage2D");
	Btk_glCreateProgram = (PFNGLCREATEPROGRAMPROC)load("glCreateProgram");
	Btk_glCreateShader = (PFNGLCREATESHADERPROC)load("glCreateShader");
	Btk_glCullFace = (PFNGLCULLFACEPROC)load("glCullFace");
	Btk_glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)load("glDeleteBuffers");
	Btk_glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)load("glDeleteFramebuffers");
	Btk_glDeleteProgram = (PFNGLDELETEPROGRAMPROC)load("glDeleteProgram");
	Btk_glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)load("glDeleteRenderbuffers");
	Btk_glDeleteShader = (PFNGLDELETESHADERPROC)load("glDeleteShader");
	Btk_glDeleteTextures = (PFNGLDELETETEXTURESPROC)load("glDeleteTextures");
	Btk_glDepthFunc = (PFNGLDEPTHFUNCPROC)load("glDepthFunc");
	Btk_glDepthMask = (PFNGLDEPTHMASKPROC)load("glDepthMask");
	Btk_glDepthRangef = (PFNGLDEPTHRANGEFPROC)load("glDepthRangef");
	Btk_glDetachShader = (PFNGLDETACHSHADERPROC)load("glDetachShader");
	Btk_glDisable = (PFNGLDISABLEPROC)load("glDisable");
	Btk_glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)load("glDisableVertexAttribArray");
	Btk_glDrawArrays = (PFNGLDRAWARRAYSPROC)load("glDrawArrays");
	Btk_glDrawElements = (PFNGLDRAWELEMENTSPROC)load("glDrawElements");
	Btk_glEnable = (PFNGLENABLEPROC)load("glEnable");
	Btk_glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)load("glEnableVertexAttribArray");
	Btk_glFinish = (PFNGLFINISHPROC)load("glFinish");
	Btk_glFlush = (PFNGLFLUSHPROC)load("glFlush");
	Btk_glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)load("glFramebufferRenderbuffer");
	Btk_glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)load("glFramebufferTexture2D");
	Btk_glFrontFace = (PFNGLFRONTFACEPROC)load("glFrontFace");
	Btk_glGenBuffers = (PFNGLGENBUFFERSPROC)load("glGenBuffers");
	Btk_glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)load("glGenerateMipmap");
	Btk_glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)load("glGenFramebuffers");
	Btk_glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)load("glGenRenderbuffers");
	Btk_glGenTextures = (PFNGLGENTEXTURESPROC)load("glGenTextures");
	Btk_glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)load("glGetActiveAttrib");
	Btk_glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)load("glGetActiveUniform");
	Btk_glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)load("glGetAttachedShaders");
	Btk_glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)load("glGetAttribLocation");
	Btk_glGetBooleanv = (PFNGLGETBOOLEANVPROC)load("glGetBooleanv");
	Btk_glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)load("glGetBufferParameteriv");
	Btk_glGetError = (PFNGLGETERRORPROC)load("glGetError");
	Btk_glGetFloatv = (PFNGLGETFLOATVPROC)load("glGetFloatv");
	Btk_glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)load("glGetFramebufferAttachmentParameteriv");
	Btk_glGetIntegerv = (PFNGLGETINTEGERVPROC)load("glGetIntegerv");
	Btk_glGetProgramiv = (PFNGLGETPROGRAMIVPROC)load("glGetProgramiv");
	Btk_glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)load("glGetProgramInfoLog");
	Btk_glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)load("glGetRenderbufferParameteriv");
	Btk_glGetShaderiv = (PFNGLGETSHADERIVPROC)load("glGetShaderiv");
	Btk_glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)load("glGetShaderInfoLog");
	Btk_glGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC)load("glGetShaderPrecisionFormat");
	Btk_glGetShaderSource = (PFNGLGETSHADERSOURCEPROC)load("glGetShaderSource");
	Btk_glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
	Btk_glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC)load("glGetTexParameterfv");
	Btk_glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC)load("glGetTexParameteriv");
	Btk_glGetUniformfv = (PFNGLGETUNIFORMFVPROC)load("glGetUniformfv");
	Btk_glGetUniformiv = (PFNGLGETUNIFORMIVPROC)load("glGetUniformiv");
	Btk_glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)load("glGetUniformLocation");
	Btk_glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC)load("glGetVertexAttribfv");
	Btk_glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC)load("glGetVertexAttribiv");
	Btk_glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC)load("glGetVertexAttribPointerv");
	Btk_glHint = (PFNGLHINTPROC)load("glHint");
	Btk_glIsBuffer = (PFNGLISBUFFERPROC)load("glIsBuffer");
	Btk_glIsEnabled = (PFNGLISENABLEDPROC)load("glIsEnabled");
	Btk_glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)load("glIsFramebuffer");
	Btk_glIsProgram = (PFNGLISPROGRAMPROC)load("glIsProgram");
	Btk_glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)load("glIsRenderbuffer");
	Btk_glIsShader = (PFNGLISSHADERPROC)load("glIsShader");
	Btk_glIsTexture = (PFNGLISTEXTUREPROC)load("glIsTexture");
	Btk_glLineWidth = (PFNGLLINEWIDTHPROC)load("glLineWidth");
	Btk_glLinkProgram = (PFNGLLINKPROGRAMPROC)load("glLinkProgram");
	Btk_glPixelStorei = (PFNGLPIXELSTOREIPROC)load("glPixelStorei");
	Btk_glPolygonOffset = (PFNGLPOLYGONOFFSETPROC)load("glPolygonOffset");
	Btk_glReadPixels = (PFNGLREADPIXELSPROC)load("glReadPixels");
	Btk_glReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC)load("glReleaseShaderCompiler");
	Btk_glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)load("glRenderbufferStorage");
	Btk_glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC)load("glSampleCoverage");
	Btk_glScissor = (PFNGLSCISSORPROC)load("glScissor");
	Btk_glShaderBinary = (PFNGLSHADERBINARYPROC)load("glShaderBinary");
	Btk_glShaderSource = (PFNGLSHADERSOURCEPROC)load("glShaderSource");
	Btk_glStencilFunc = (PFNGLSTENCILFUNCPROC)load("glStencilFunc");
	Btk_glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC)load("glStencilFuncSeparate");
	Btk_glStencilMask = (PFNGLSTENCILMASKPROC)load("glStencilMask");
	Btk_glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC)load("glStencilMaskSeparate");
	Btk_glStencilOp = (PFNGLSTENCILOPPROC)load("glStencilOp");
	Btk_glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC)load("glStencilOpSeparate");
	Btk_glTexImage2D = (PFNGLTEXIMAGE2DPROC)load("glTexImage2D");
	Btk_glTexParameterf = (PFNGLTEXPARAMETERFPROC)load("glTexParameterf");
	Btk_glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)load("glTexParameterfv");
	Btk_glTexParameteri = (PFNGLTEXPARAMETERIPROC)load("glTexParameteri");
	Btk_glTexParameteriv = (PFNGLTEXPARAMETERIVPROC)load("glTexParameteriv");
	Btk_glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)load("glTexSubImage2D");
	Btk_glUniform1f = (PFNGLUNIFORM1FPROC)load("glUniform1f");
	Btk_glUniform1fv = (PFNGLUNIFORM1FVPROC)load("glUniform1fv");
	Btk_glUniform1i = (PFNGLUNIFORM1IPROC)load("glUniform1i");
	Btk_glUniform1iv = (PFNGLUNIFORM1IVPROC)load("glUniform1iv");
	Btk_glUniform2f = (PFNGLUNIFORM2FPROC)load("glUniform2f");
	Btk_glUniform2fv = (PFNGLUNIFORM2FVPROC)load("glUniform2fv");
	Btk_glUniform2i = (PFNGLUNIFORM2IPROC)load("glUniform2i");
	Btk_glUniform2iv = (PFNGLUNIFORM2IVPROC)load("glUniform2iv");
	Btk_glUniform3f = (PFNGLUNIFORM3FPROC)load("glUniform3f");
	Btk_glUniform3fv = (PFNGLUNIFORM3FVPROC)load("glUniform3fv");
	Btk_glUniform3i = (PFNGLUNIFORM3IPROC)load("glUniform3i");
	Btk_glUniform3iv = (PFNGLUNIFORM3IVPROC)load("glUniform3iv");
	Btk_glUniform4f = (PFNGLUNIFORM4FPROC)load("glUniform4f");
	Btk_glUniform4fv = (PFNGLUNIFORM4FVPROC)load("glUniform4fv");
	Btk_glUniform4i = (PFNGLUNIFORM4IPROC)load("glUniform4i");
	Btk_glUniform4iv = (PFNGLUNIFORM4IVPROC)load("glUniform4iv");
	Btk_glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)load("glUniformMatrix2fv");
	Btk_glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)load("glUniformMatrix3fv");
	Btk_glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)load("glUniformMatrix4fv");
	Btk_glUseProgram = (PFNGLUSEPROGRAMPROC)load("glUseProgram");
	Btk_glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)load("glValidateProgram");
	Btk_glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)load("glVertexAttrib1f");
	Btk_glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)load("glVertexAttrib1fv");
	Btk_glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC)load("glVertexAttrib2f");
	Btk_glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC)load("glVertexAttrib2fv");
	Btk_glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC)load("glVertexAttrib3f");
	Btk_glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC)load("glVertexAttrib3fv");
	Btk_glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC)load("glVertexAttrib4f");
	Btk_glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC)load("glVertexAttrib4fv");
	Btk_glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)load("glVertexAttribPointer");
	Btk_glViewport = (PFNGLVIEWPORTPROC)load("glViewport");
}
static int find_extensionsGLES2(void) {
	if (!get_exts()) return 0;
	(void)&has_ext;
	free_exts();
	return 1;
}

static void find_coreGLES2(void) {

    /* Thank you @elmindreda
     * https://github.com/elmindreda/greg/blob/master/templates/greg.c.in#L176
     * https://github.com/glfw/glfw/blob/master/src/context.c#L36
     */
    int i, major, minor;

    const char* version;
    const char* prefixes[] = {
        "OpenGL ES-CM ",
        "OpenGL ES-CL ",
        "OpenGL ES ",
        NULL
    };

    version = (const char*) glGetString(GL_VERSION);
    if (!version) return;

    for (i = 0;  prefixes[i];  i++) {
        const size_t length = strlen(prefixes[i]);
        if (strncmp(version, prefixes[i], length) == 0) {
            version += length;
            break;
        }
    }

/* PR #18 */
#ifdef _MSC_VER
    sscanf_s(version, "%d.%d", &major, &minor);
#else
    sscanf(version, "%d.%d", &major, &minor);
#endif

    GLVersion.major = major; GLVersion.minor = minor;
    max_loaded_major = major; max_loaded_minor = minor;
	GLAD_GL_ES_VERSION_2_0 = (major == 2 && minor >= 0) || major > 2;
	if (GLVersion.major > 2 || (GLVersion.major >= 2 && GLVersion.minor >= 0)) {
		max_loaded_major = 2;
		max_loaded_minor = 0;
	}
}

int BtkLoadGLES2Loader(GLADloadproc load) {
	//FIXME Why in glGetString(GL_VERSION) == NULLPTR
	//When we load glad before GL_CreateContext
	load_GL_ES_VERSION_2_0(load);

	GLVersion.major = 0; GLVersion.minor = 0;
	glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
	if(glGetString == NULL) return 0;
	if(glGetString(GL_VERSION) == NULL) return 0;
	find_coreGLES2();
	//load_GL_ES_VERSION_2_0(load);

	if (!find_extensionsGLES2()) return 0;
	return GLVersion.major != 0 || GLVersion.minor != 0;
}

