/* Generated by dllimport.py */
#include <Btk/impl/loadso.hpp>
#include <Btk/impl/scope.hpp>

#ifdef BTK_PNG_DYMAIC
    #define BTK_PNG_LOAD()   _lib_PNG.load()
    #define BTK_PNG_UNLOAD() _lib_PNG.unload()
#else
    #define BTK_PNG_LOAD()   
    #define BTK_PNG_UNLOAD()   
#endif

//Platform depended dymaic library path
#ifdef __WIN32
    #define BTK_PNG_LIBNAME "png.dll"
#endif
#ifdef __linux
    #define BTK_PNG_LIBNAME "libpng.so"
#endif

#ifdef BTK_PNG_DYMAIC
//Library Elem
struct _PNGLibrary {
    BTK_DYMAIC_LIBRARY(BTK_PNG_LIBNAME);
    BTK_DYMAIC_FUNCTION(png_create_info_struct);
    BTK_DYMAIC_FUNCTION(png_create_read_struct);
    BTK_DYMAIC_FUNCTION(png_destroy_info_struct);
    BTK_DYMAIC_FUNCTION(png_destroy_read_struct);
    BTK_DYMAIC_FUNCTION(png_get_IHDR);
    BTK_DYMAIC_FUNCTION(png_get_io_ptr);
    BTK_DYMAIC_FUNCTION(png_get_channels);
    BTK_DYMAIC_FUNCTION(png_get_PLTE);
    BTK_DYMAIC_FUNCTION(png_get_tRNS);
    BTK_DYMAIC_FUNCTION(png_get_valid);
    BTK_DYMAIC_FUNCTION(png_read_image);
    BTK_DYMAIC_FUNCTION(png_read_info);
    BTK_DYMAIC_FUNCTION(png_read_update_info);
    BTK_DYMAIC_FUNCTION(png_set_sig_bytes);
    BTK_DYMAIC_FUNCTION(png_set_expand);
    BTK_DYMAIC_FUNCTION(png_set_gray_to_rgb);
    BTK_DYMAIC_FUNCTION(png_set_packing);
    BTK_DYMAIC_FUNCTION(png_set_longjmp_fn);
    BTK_DYMAIC_FUNCTION(png_set_read_fn);
    BTK_DYMAIC_FUNCTION(png_set_strip_16);
    BTK_DYMAIC_FUNCTION(png_set_interlace_handling);
    BTK_DYMAIC_FUNCTION(png_sig_cmp);
    BTK_DYMAIC_FUNCTION(png_error);
    BTK_DYMAIC_FUNCTION(png_create_write_struct);
    BTK_DYMAIC_FUNCTION(png_destroy_write_struct);
    BTK_DYMAIC_FUNCTION(png_set_write_fn);
    BTK_DYMAIC_FUNCTION(png_set_IHDR);
    BTK_DYMAIC_FUNCTION(png_write_info);
    BTK_DYMAIC_FUNCTION(png_set_rows);
    BTK_DYMAIC_FUNCTION(png_write_png);
    BTK_DYMAIC_FUNCTION(png_set_PLTE);
};
BTK_MAKE_DYLIB(_PNGLibrary,_lib_PNG);
//Function macro
#define png_create_info_struct _lib_PNG->png_create_info_struct
#define png_create_read_struct _lib_PNG->png_create_read_struct
#define png_destroy_info_struct _lib_PNG->png_destroy_info_struct
#define png_destroy_read_struct _lib_PNG->png_destroy_read_struct
#define png_get_IHDR _lib_PNG->png_get_IHDR
#define png_get_io_ptr _lib_PNG->png_get_io_ptr
#define png_get_channels _lib_PNG->png_get_channels
#define png_get_PLTE _lib_PNG->png_get_PLTE
#define png_get_tRNS _lib_PNG->png_get_tRNS
#define png_get_valid _lib_PNG->png_get_valid
#define png_read_image _lib_PNG->png_read_image
#define png_read_info _lib_PNG->png_read_info
#define png_read_update_info _lib_PNG->png_read_update_info
#define png_set_sig_bytes _lib_PNG->png_set_sig_bytes
#define png_set_expand _lib_PNG->png_set_expand
#define png_set_gray_to_rgb _lib_PNG->png_set_gray_to_rgb
#define png_set_packing _lib_PNG->png_set_packing
#define png_set_longjmp_fn _lib_PNG->png_set_longjmp_fn
#define png_set_read_fn _lib_PNG->png_set_read_fn
#define png_set_strip_16 _lib_PNG->png_set_strip_16
#define png_set_interlace_handling _lib_PNG->png_set_interlace_handling
#define png_sig_cmp _lib_PNG->png_sig_cmp
#define png_error _lib_PNG->png_error
#define png_create_write_struct _lib_PNG->png_create_write_struct
#define png_destroy_write_struct _lib_PNG->png_destroy_write_struct
#define png_set_write_fn _lib_PNG->png_set_write_fn
#define png_set_IHDR _lib_PNG->png_set_IHDR
#define png_write_info _lib_PNG->png_write_info
#define png_set_rows _lib_PNG->png_set_rows
#define png_write_png _lib_PNG->png_write_png
#define png_set_PLTE _lib_PNG->png_set_PLTE
#endif