/* Generated by dllimport.py */
#include <Btk/detail/loadso.hpp>
#include <Btk/detail/scope.hpp>

#ifdef BTK_WEBP_DYMAIC
    #define BTK_WEBP_LOAD()   _lib_WEBP.load()
    #define BTK_WEBP_UNLOAD() _lib_WEBP.unload()
#else
    #define BTK_WEBP_LOAD()   
    #define BTK_WEBP_UNLOAD()   
#endif

//Platform depended dymaic library path
#ifdef __WIN32
    #define BTK_WEBP_LIBNAME "webp.dll"
#endif
#ifdef __linux
    #define BTK_WEBP_LIBNAME "libwebp.so"
#endif

#ifdef BTK_WEBP_DYMAIC
//Library Elem
struct _WEBPLibrary {
    BTK_DYMAIC_LIBRARY(BTK_WEBP_LIBNAME);
    BTK_DYMAIC_FUNCTION(WebPInitDecoderConfigInternal);
    BTK_DYMAIC_FUNCTION(WebPDecode);
    BTK_DYMAIC_FUNCTION(WebPFreeDecBuffer);
    BTK_DYMAIC_FUNCTION(WebPConfigInitInternal);
    BTK_DYMAIC_FUNCTION(WebPPictureInitInternal);
    BTK_DYMAIC_FUNCTION(WebPPictureAlloc);
    BTK_DYMAIC_FUNCTION(WebPPictureImportRGBA);
    BTK_DYMAIC_FUNCTION(WebPEncode);
    BTK_DYMAIC_FUNCTION(WebPPictureFree);
};
BTK_MAKE_DYLIB(_WEBPLibrary,_lib_WEBP);
//Function macro
#define WebPInitDecoderConfigInternal _lib_WEBP->WebPInitDecoderConfigInternal
#define WebPDecode _lib_WEBP->WebPDecode
#define WebPFreeDecBuffer _lib_WEBP->WebPFreeDecBuffer
#define WebPConfigInitInternal _lib_WEBP->WebPConfigInitInternal
#define WebPPictureInitInternal _lib_WEBP->WebPPictureInitInternal
#define WebPPictureAlloc _lib_WEBP->WebPPictureAlloc
#define WebPPictureImportRGBA _lib_WEBP->WebPPictureImportRGBA
#define WebPEncode _lib_WEBP->WebPEncode
#define WebPPictureFree _lib_WEBP->WebPPictureFree
#endif
