name: C/C++ CI on Windows
on: [push]

jobs:
  build:
    name: Build Btk
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
      # The version to use. Should be a semver range or 'latest'. Or use branch@{branch_name} to select a branch.
        xmake-version: latest
    - name: Build release
      run: xmake -y
    - name: update release
      uses: actions/upload-artifact@v2
      with:
          name: btk.dll
          path: ./build/windows/x64/release/btk.dll
